apiVersion: v1
kind: ConfigMap
metadata:
  name: delegate-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  proxy.conf: "server { root /www/data;proxy_http_version 1.1;\n}"
{{- if .Values.additionalConfigs }}
{{- toYaml .Values.additionalConfigs | nindent 2 }}
{{- end }}