apiVersion: v1
kind: ConfigMap
metadata:
  name: cv-nextgen
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  DEPLOY_MODE: '{{ .Values.config.DEPLOY_MODE }}'
  ENV: '{{ .Values.config.ENV }}'
  LOGGING_LEVEL: '{{ .Values.appLogLevel }}'
  MANAGER_URL: http://harness-manager.{{ .Release.Namespace }}.svc.cluster.local:9090/
  NG_MANAGER_URL: http://ng-manager.{{ .Release.Namespace }}.svc.cluster.local:7090/
  MEMORY: '{{ .Values.java.memory }}'
  STACK_DRIVER_LOGGING_ENABLED: '{{ .Values.global.stackDriverLoggingEnabled }}'
  VERIFICATION_PORT: '{{ .Values.config.VERIFICATION_PORT }}'
  NOTIFICATION_BASE_URL: http://platform-service.{{ .Release.Namespace }}.svc.cluster.local:9005/api/
  SHOULD_CONFIGURE_WITH_NOTIFICATION: '{{ .Values.config.SHOULD_CONFIGURE_WITH_NOTIFICATION }}'
  PORTAL_URL: '{{ .Values.global.loadbalancerURL }}'
  MANAGER_CLIENT_BASEURL: http://harness-manager.{{ .Release.Namespace }}.svc.cluster.local:9090/
  ET_SERVICE_BASE_URL: http://et-service.{{ .Release.Namespace }}.svc.cluster.local:9191/api/
  EVENTS_FRAMEWORK_REDIS_URL: '{{ include "harnesscommon.dbv3.redisConnection" (dict "ctx" $ "database" "eventsFramework") }}'
  EVENTS_FRAMEWORK_USE_SENTINEL: {{ include "harnesscommon.dbv3.useRedisSentinels"  (dict "ctx" $ "database" "eventsFramework") }}
  EVENTS_FRAMEWORK_SENTINEL_MASTER_NAME: 'harness-redis'
  EVENTS_FRAMEWORK_REDIS_SENTINELS: '{{ include "harnesscommon.dbv3.redisConnection" (dict "ctx" $ "database" "eventsFramework") }}'
  SHOULD_CONFIGURE_WITH_PMS: "true"
  LOCK_CONFIG_REDIS_SENTINELS: '{{ include "harnesscommon.dbv3.redisConnection" (dict "ctx" $ "database" "lockConfig") }}'
  LOCK_CONFIG_SENTINEL_MASTER_NAME: harness-redis
  LOCK_CONFIG_USE_SENTINEL:  {{ include "harnesscommon.dbv3.useRedisSentinels"  (dict "ctx" $ "database" "lockConfig") }}
  PMS_TARGET: pipeline-service:12011
  PMS_AUTHORITY: pipeline-service:12011
  GRPC_SERVER_PORT: "9979"
  CACHE_CONFIG_REDIS_URL: '{{ include "harnesscommon.dbv3.redisConnection" (dict "ctx" $ "database" "cacheConfig") }}'
  CACHE_BACKEND: "REDIS"
  CACHE_CONFIG_REDIS_SENTINELS: '{{ include "harnesscommon.dbv3.redisConnection" (dict "ctx" $ "database" "cacheConfig") }}'
  CACHE_CONFIG_SENTINEL_MASTER_NAME: "harness-redis"
  CACHE_CONFIG_USE_SENTINEL:  {{ include "harnesscommon.dbv3.useRedisSentinels"  (dict "ctx" $ "database" "cacheConfig") }}
  LOCK_CONFIG_REDIS_URL: '{{ include "harnesscommon.dbv3.redisConnection" (dict "ctx" $ "database" "lockConfig") }}'
  MOCK_ACCESS_CONTROL_SERVICE: "false"
  ACCESS_CONTROL_BASE_URL:  http://access-control.{{ .Release.Namespace }}.svc.cluster.local:9006/api/
  ACCESS_CONTROL_ENABLED: '{{ .Values.config.ACCESS_CONTROL_ENABLED }}'
  ENABLE_DASHBOARD_TIMESCALE: "true"
  ENABLE_AUDIT: "true"
  AUDIT_CLIENT_BASEURL: 'http://platform-service.{{ .Release.Namespace }}.svc.cluster.local:9005/api/'
  WEBHOOK_BASEURL: '{{ .Values.global.loadbalancerURL }}/gateway/cv/api/'
  {{ include "harnesscommon.harnessfunctions.java17flags" (dict "context" $) | nindent 2 }}
  {{- if .Values.additionalConfigs }}
  {{- toYaml .Values.additionalConfigs | nindent 2 }}
  {{- end }}
