DOCKER_FILE_PATH: /harness/harness-core/dockerization/ng-manager/Dockerfile-ng-manager-cie-jdk-multistage
CONTEXT_PATH: /harness/harness-core
HELM_CHART_SOURCE_DIRECTORY: harness-core/120-ng-manager/chart
