apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: event-service
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "event-service.selectorLabels" . | nindent 6 }}
