ARTIFACT_REPO: harness/feature-manager-openjdk-8u242
HELM_CHART_SOURCE_DIRECTORY: harness-core/360-cg-manager/chart
HELM_REPO_NAME: us-west1-docker.pkg.dev/platform-205701/harness-helm-artifacts
BUILD_STEP_RESOURCE_CPU: 1000m
BUILD_STEP_RESOURCE_MEMORY: 4Gi

