BUILD_SCRIPT_PATH: 360-cg-manager/build/feature_build.sh
DOCKER_FILE_PATH: /harness/harness-core/dist/manager/Dockerfile-cie-jdk
CONTEXT_PATH: /harness/harness-core/dist/manager
ARTIFACT_REPO: harness/feature-manager-openjdk-8u242
HELM_CHART_SOURCE_DIRECTORY: harness-core/360-cg-manager/chart
HELM_REPO_NAME: us-west1-docker.pkg.dev/platform-205701/harness-helm-artifacts
BUILD_STEP_RESOURCE_CPU: 1000m
BUILD_STEP_RESOURCE_MEMORY: 4Gi
