DOCKER_FILE_PATH: /harness/harness-core/dockerization/change-data-capture/Dockerfile-change-data-capture-multistage
CONTEXT_PATH: /harness/harness-core
HELM_CHART_SOURCE_DIRECTORY: harness-core/110-change-data-capture/chart
