ARTIFACT_REPO: harness/feature-change-data-capture-openjdk-8u242
HELM_CHART_SOURCE_DIRECTORY: harness-core/110-change-data-capture/chart
HELM_REPO_NAME: us-west1-docker.pkg.dev/platform-205701/harness-helm-artifacts
BUILD_STEP_RESOURCE_CPU: 1000m
BUILD_STEP_RESOURCE_MEMORY: 4Gi