apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: migrator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotation }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotation "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  minAvailable: "50%"
  selector:
   matchLabels:
    app: migrator
