apiVersion: v1
kind: Secret
metadata:
  name: {{ include "migrator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "migrator.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotation }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotation "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- include "migrator.generateSecrets" . }}