openapi: 3.0.0
x-stoplight:
  id: 9n2ahxgr7ormg
info:
  title: Harness NextGen Software Delivery Platform API Reference
  version: '1.0'
  description: This is the Open Api Spec 3 for the SSCA Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
  contact:
    email: contact@harness.io
servers:
  - url: 'https://app.harness.io'
    description: Harness host URL.
paths:
  '/v1/org/{org}/project/{project}/sbom/process':
    parameters:
      - $ref: '#/components/parameters/OrgParam'
      - $ref: '#/components/parameters/ProjectParam'
    post:
      summary: process raw SBOM into harness usable normalized form
      operationId: process-sbom
      responses:
        '200':
          $ref: '#/components/responses/SbomProcessResponseBody'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        '502':
          description: Bad Gateway
      description: process & inject sbom
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/SbomProcessRequestBody'
      tags:
        - sbomProcessor
      security:
        - x-api-key: []
  '/v1/org/{org}/project/{project}/sbom/enforcement':
    parameters:
      - $ref: '#/components/parameters/OrgParam'
      - $ref: '#/components/parameters/ProjectParam'
    post:
      summary: enforce normalized SBOM based on policies applied
      operationId: enforce-sbom
      responses:
        '200':
          $ref: '#/components/responses/EnforceSbomResponseBody'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        '502':
          description: Bad Gateway
      description: enforce an sbom
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/EnforceSbomRequestBody'
      tags:
        - sbomProcessor
      security:
        - x-api-key: []
  /v1/token:
    get:
      summary: Issue a cross-service token
      tags:
        - Token
      responses:
        '200':
          $ref: '#/components/responses/TokenIssueResponseBody'
      operationId: Token#IssueToken
      x-stoplight:
        id: 2fi6nxijk1nay
      description: Issue a cross-service token
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      x-internal: true
      security:
        - x-api-key: []
  '/v1/org/{org}/project/{project}/orchestration/{orchestration-id}/sbom-download':
    get:
      summary: Download SBOM for an artifact
      responses:
        '200':
          $ref: '#/components/responses/ArtifactSbomResponseBody'
      operationId: downloadSbom
      x-stoplight:
        id: 65dvz43ksx8pa
      description: Download SBOM for an artifact
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      x-internal: true
      security:
        - x-api-key: []
      tags:
        - orchestration
    parameters:
      - $ref: '#/components/parameters/OrgParam'
      - $ref: '#/components/parameters/ProjectParam'
      - schema:
          type: string
        name: orchestration-id
        in: path
        required: true
        description: Orchestration Identifier
  '/v1/org/{org}/project/{project}/orchestration/{orchestration-id}/summary':
    parameters:
      - $ref: '#/components/parameters/OrgParam'
      - $ref: '#/components/parameters/ProjectParam'
      - schema:
          type: string
        name: orchestration-id
        in: path
        required: true
    get:
      summary: Get Orchestration Summary
      responses:
        '200':
          $ref: '#/components/responses/OrchestrationSummaryResponseBody'
      operationId: getOrchestrationSummary
      x-stoplight:
        id: 0dnpkug4d1z89
      description: Get Orchestration Summary
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      x-internal: true
      tags:
        - orchestration
  '/v1/org/{org}/project/{project}/enforcement/{enforcement-id}/summary':
    parameters:
      - $ref: '#/components/parameters/OrgParam'
      - $ref: '#/components/parameters/ProjectParam'
      - schema:
          type: string
        name: enforcement-id
        in: path
        required: true
    get:
      summary: Get Enforcement Summary
      responses:
        '200':
          $ref: '#/components/responses/EnforcementSummaryResponseBody'
      operationId: getEnforcementSummary
      x-stoplight:
        id: mq79kp83fd5m6
      description: Get Enforcement Summary
      security:
        - x-api-key: []
      tags:
        - enforcement
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
  '/v1/org/{org}/project/{project}/enforcement/{enforcement-id}/policy-violations':
    get:
      summary: List Policy Violations
      tags:
        - enforcement
      responses:
        '200':
          $ref: '#/components/responses/PolicyViolationResponse'
      operationId: getPolicyViolations
      x-stoplight:
        id: ybu535bybekmz
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Order'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/Sort'
        - schema:
            type: string
          in: query
          name: search_text
          description: Text on the basis of which results will be filtered
    parameters:
      - $ref: '#/components/parameters/OrgParam'
      - $ref: '#/components/parameters/ProjectParam'
      - schema:
          type: string
        name: enforcement-id
        in: path
        required: true
        description: Enforcement Identifier
components:
  schemas:
    Artifact:
      title: Artifact
      x-stoplight:
        id: a4wwyrfywvqai
      type: object
      x-examples: {}
      properties:
        id:
          type: string
          description: id of the artifact
          example: 089855ea-f90e-4bea-a5c9-b5ddf85d3180
        type:
          type: string
          description: type of the artifact
          example: repo/image
        name:
          type: string
          description: name of the artifact
          example: harness/image
        tag:
          type: string
          description: tag of the artifact
          default: latest
          example: latest
        registry_url:
          type: string
          description: url of the artifact
          example: 'https://console.cloud.google.com/gcr/images/imageName'
      required:
        - name
        - registry_url
    SbomProcess:
      title: SbomProcess
      x-stoplight:
        id: d6f21w8o0f15z
      type: object
      properties:
        name:
          type: string
          description: name of the sbom
          example: SBOM_Name
        data:
          type: string
          format: byte
          description: serialised sbom data
        format:
          type: string
          description: format of the SBOM
          example: spdx-json
        url:
          type: string
          description: URL of the sbom
          example: 'https://console.google.com/storage'
      required:
        - name
        - format
    Attestation:
      title: Attestation
      x-stoplight:
        id: 2pcamdjrm07w0
      type: object
      properties:
        is_attested:
          type: boolean
          default: false
          description: is the sbom attested or not
        url:
          type: string
          description: url of the attested file
          example: 'https://storage.googleapis.com/sbom_store_public/kmpySmUISimoRrJL6NL73w/default/SSCS_CI_Plugin_Demo/CKO_SSCA_Pipeline/Build/39/q940CvjoQj-GEInJQfWiwg/sbom'
    SbomMetadata:
      title: SbomMetadata
      x-stoplight:
        id: lf9igo6vtrj1c
      type: object
      properties:
        format:
          type: string
          description: stage name where sbom is generated
          minLength: 3
          example: spdx-json
        tool:
          type: string
          description: name of the package
          minLength: 3
          example: synk
        pipeline_execution_id:
          type: string
          description: name of the package
          example: z940CvjoQj-GEInJQfWiwq
          minLength: 3
        sequence_id:
          type: string
          description: name of the package
          example: '1'
        pipeline_identifier:
          type: string
          description: name of the package
          example: SSCA_Pipeline
          minLength: 3
        stage_identifier:
          type: string
          description: name of the Stage
          example: Build
        step_identifier:
          type: string
          description: id of the step
          example: Orchestrate
        build_url:
          type: string
          description: BuildURL
          example: 'https://app.harness.io/ng/#/account/acc/ci/orgs/org/projects/dummyProject/pipelines/CKO_SSCA_Pipeline/executions/q940CvjoQj-GEInJQfWiwg/pipeline?storeType=INLINE'
        step_execution_id:
          type: string
          description: StepExecutionId
          example: betatest1
    SbomProcessRequestBody:
      title: SbomProcessRequestBody
      x-stoplight:
        id: 61mbk42tf3c3h
      type: object
      properties:
        artifact:
          $ref: '#/components/schemas/Artifact'
        sbom_process:
          $ref: '#/components/schemas/SbomProcess'
        attestation:
          $ref: '#/components/schemas/Attestation'
        sbom_metadata:
          $ref: '#/components/schemas/SbomMetadata'
    SbomProcessResponseBody:
      title: SbomProcessResponseBody
      x-stoplight:
        id: zcgp4uyfw7bpy
      type: object
      properties:
        artifact_id:
          type: string
          description: Id of created artifact
    EnforceSbomResponseBody:
      title: SbomEnforceResponseBody
      x-stoplight:
        id: 1scxbhuitxmoa
      type: object
      properties:
        enforcement_id:
          type: string
          description: ID of the enforcement of the SBOM
        status:
          type: string
          description: Status of the enforcement
      required:
        - enforcement_id
    EnforceSbomRequestBody:
      title: SbomEnforceRequestBody
      x-stoplight:
        id: ytvy1p0bfq511
      type: object
      properties:
        enforcement_id:
          type: string
        artifact:
          $ref: '#/components/schemas/Artifact'
        policy_file_id:
          type: string
    TokenIssueResponseBody:
      title: TokenIssueResponseBody
      x-stoplight:
        id: 50ub6j4mwcwvm
      type: object
      x-internal: true
      properties:
        token:
          type: string
          description: Issued cross-service JWT
      required:
        - token
    TokenIssueTokenResponseBody:
      type: object
      properties:
        token:
          type: string
          x-stoplight:
            id: uampvshmkin55
          description: Issued cross-service JWT
      required:
        - token
      title: ''
      x-internal: true
    ArtifactSbomResponseBody:
      title: ArtifactSbomResponseBody
      x-stoplight:
        id: kubfwxzoybmsz
      type: object
      properties:
        sbom:
          type: string
      description: ''
    OrchestrationSummaryResponse:
      title: OrchestrationSummary
      x-stoplight:
        id: 0dw25w343ec9r
      type: object
      properties:
        step_execution_id:
          type: string
          x-stoplight:
            id: re9hzrx76pcq9
        is_attested:
          x-stoplight:
            id: mkozs6n2tcvg0
          type: boolean
        artifact:
          $ref: '#/components/schemas/Artifact'
        sbom:
          $ref: '#/components/schemas/SbomDetails'
    EnforcementSummaryResponse:
      title: EnforcementSummaryResponse
      x-stoplight:
        id: nwebeu4hidgsg
      type: object
      properties:
        artifact:
          $ref: '#/components/schemas/Artifact'
        enforcement_id:
          type: string
          x-stoplight:
            id: nne3xm3qiinrd
        allow_list_violation_count:
          type: integer
          x-stoplight:
            id: 4ibwo3jt9zryz
        deny_list_violation_count:
          type: integer
          x-stoplight:
            id: 56nfq8nop5zpq
        status:
          type: string
          x-stoplight:
            id: oa150xvsbdv6d
      description: Enforcement Summary
    SbomDetails:
      title: SbomDetails
      x-stoplight:
        id: qsjqd2hso1qau
      type: object
      description: Sbom Details
      properties:
        name:
          type: string
          x-stoplight:
            id: wfr4gq9d52on6
      required:
        - name
    PolicyViolation:
      type: object
      x-examples: {}
      properties:
        enforcement_id:
          type: string
          x-stoplight:
            id: 3e2fxcj7hjpe3
        artifact_id:
          type: string
          x-stoplight:
            id: xxn3q6q77l8h3
        tag:
          type: string
        image_name:
          type: string
          x-stoplight:
            id: 1556dbzulzbr2
        account:
          type: string
          x-stoplight:
            id: et1yzgfotca96
        org:
          type: string
          x-stoplight:
            id: xtzli0ovtjy9m
        project:
          type: string
          x-stoplight:
            id: 9kx3do1jkk50k
        orchestration_id:
          type: string
          x-stoplight:
            id: p3pxleq3kppsj
        violation_type:
          type: string
          x-stoplight:
            id: sf8chofpv0xi6
        violation_details:
          type: string
          x-stoplight:
            id: 2avuqif52p9gg
        name:
          type: string
        version:
          type: string
        supplier:
          type: string
        supplier_type:
          type: string
          x-stoplight:
            id: 3jkl2h67d540q
        package_manager:
          type: string
          x-stoplight:
            id: ko7cdmfu7uhm5
        license:
          type: array
          items:
            type: string
        purl:
          type: string
      title: ''
  parameters:
    OrgParam:
      name: org
      in: path
      required: true
      schema:
        type: string
      description: Harness Organization Id
    ProjectParam:
      in: path
      required: true
      schema:
        type: string
      description: Harness Project Id
      name: project
    AccountHeader:
      name: Harness-Account
      in: header
      required: false
      schema:
        type: string
      description: 'Identifier field of the account the resource is scoped to. This is required for Authorization methods other than the x-api-key header. If you are using the x-api-key header, this can be skipped.'
    Limit:
      name: limit
      in: query
      schema:
        type: integer
        default: 30
        maximum: 1000
      description: Number of items to return per page.
    Order:
      name: order
      in: query
      required: false
      schema:
        type: string
        enum:
          - ASC
          - DESC
        default: ASC
      description: Order on the basis of which sorting is done.
    Page:
      name: page
      in: query
      required: false
      schema:
        type: integer
        default: 0
      description: "Pagination page number strategy: Specify the page number within the paginated collection related to the number of items in each page\t"
    Sort:
      name: sort
      in: query
      required: false
      schema:
        type: string
        enum:
          - name
          - identifier
          - created
          - updated
          - license
          - supplier
        default: name
      description: Parameter on the basis of which sorting is done.
  requestBodies:
    SbomProcessRequestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SbomProcessRequestBody'
    EnforceSbomRequestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EnforceSbomRequestBody'
  securitySchemes:
    x-api-key:
      name: x-api-key
      type: apiKey
      in: header
      description: API key1 is a token provided while making the API calls. This is used to authenticate the client at the exposed endpoint.
  responses:
    SbomProcessResponseBody:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SbomProcessResponseBody'
    EnforceSbomResponseBody:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EnforceSbomResponseBody'
    TokenIssueResponseBody:
      description: Response body for token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TokenIssueResponseBody'
    ArtifactSbomResponseBody:
      description: Response Body for Artifact Sbom
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ArtifactSbomResponseBody'
    OrchestrationSummaryResponseBody:
      description: Step Execution Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OrchestrationSummaryResponse'
    EnforcementSummaryResponseBody:
      description: Enforcement Summary Response Body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EnforcementSummaryResponse'
    PolicyViolationResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/PolicyViolation'
      headers:
        X-Total-Elements:
          schema:
            type: integer
          description: Total number of elements returned in Paginated response.
        X-Page-Number:
          schema:
            type: integer
          description: Page number in Paginated response.
        X-Page-Size:
          schema:
            type: integer
          description: Maximum page size in Paginated response.
tags:
  - name: sbomProcessor
