# Default values for debezium-service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets
# --global.imageRegistry Global Docker image registry
# --global.imagePullSecrets Global Docker registry secret names as an array
# --global.storageClass Global StorageClass for Persistent Volume(s)
java:
  memory: "4096m"
#secrets:
#  default:
#    CF_CLIENT_API_KEY: "dOkdsVqdRPPRJG31XU0qY4MPqmBBMk0PTAGIKM6O7TGqhjyxScIdJe80mwh5Yb5zF3KxYBHw6B3Lfzlq"
service:
  annotations: {}
autoscaling:
  enabled: false
redis:
  secrets:
    kubernetesSecrets:
      - secretName: ""
        keys:
          REDIS_USERNAME: ""
          REDIS_PASSWORD: ""
#    secretManagement:
#      externalSecretsOperator:
#        - secretStore:
#            name: ""
#            kind: ""
#          remoteKeys:
#            REDIS_USERNAME:
#              name: ""
#              property: ""
#            REDIS_PASSWORD:
#              name: ""
#              property: ""
waitForInitContainer:
  image:
    registry: docker.io
    repository: harness/helm-init-container
    pullPolicy: IfNotPresent
    tag: "latest"
    digest: ""
    imagePullSecrets: []
image:
  registry: docker.io
  digest: ""
  repository: harness/pipeline-service-signed
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.41.3"
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "harness-default"
readinessProbe:
  httpGet:
    path: /api/health
    port: http-pms
  timeoutSeconds: 2
  periodSeconds: 5
  failureThreshold: 5
livenessProbe:
  httpGet:
    path: /api/health
    port: http-pms
  timeoutSeconds: 2
  periodSeconds: 10
  failureThreshold: 5
startupProbe:
  httpGet:
    path: /api/health
    port: http-pms
  timeoutSeconds: 2
  periodSeconds: 10
  failureThreshold: 25
global:
  ingress:
    # -- create ingress objects
    enabled: false
  commonAnnotations: {}
  commonLabels: {}
  database:
    redis:
      installed: true
    mongo:
      installed: true
  stackDriverLoggingEnabled: false
  IS_ENABLED_PIPELINE: false
  #TODO: Set these values when IS_ENABLED_PIPELINE is set to true.
#  MONGODB_SSL_ENABLED_PIPELINE: ""
#  COLLECTION_INCLUDE_LIST_PIPELINE: ""
#  DEBEZIUM_NAME_PIPELINE: ""
#  MONGODB_NAME_PIPELINE: ""
#  DATABASE_INCLUDE_LIST_PIPELINE: ""
#  REDIS_STREAM_SIZE_PIPELINE: ""
#  SNAPSHOT_MODE_PIPELINE: ""
#  MAX_QUEUE_SIZE_PIPELINE: ""
#  MAX_BATCH_SIZE_PIPELINE: ""
#  MAX_QUEUE_SIZE_IN_BYTES_PIPELINE: ""
#  POLL_INTERVAL_MS_PIPELINE: ""
#  FIELD_EXCLUDE_LIST_PIPELINE: ""
#  MONGODB_CONNECTION_STRING_PIPELINE: ""
#  LIST_OF_ERROR_CODES_FOR_OFFSET_RESET: ""

  IS_ENABLED_APPLICATIONS: false
  #TODO: Set these values when IS_ENABLED_APPLICATIONS is set to true.
#  MONGODB_SSL_ENABLED_APPLICATIONS: ""
#  COLLECTION_INCLUDE_LIST_APPLICATIONS: ""
#  DEBEZIUM_NAME_APPLICATIONS: ""
#  MONGODB_NAME_APPLICATIONS: ""
#  DATABASE_INCLUDE_LIST_APPLICATIONS: ""
#  REDIS_STREAM_SIZE_APPLICATIONS: ""
#  SNAPSHOT_MODE_APPLICATIONS: ""
#  MAX_QUEUE_SIZE_APPLICATIONS: ""
#  MAX_BATCH_SIZE_APPLICATIONS: ""
#  MAX_QUEUE_SIZE_IN_BYTES_APPLICATIONS: ""
#  POLL_INTERVAL_MS_APPLICATIONS: ""
#  FIELD_EXCLUDE_LIST_APPLICATIONS: ""
#  MONGODB_CONNECTION_STRING_APPLICATIONS: ""

  IS_ENABLED_PIPELINE_SNAPSHOT: false
  #TODO: Set these values when IS_ENABLED_PIPELINE_SNAPSHOT is set to true.
#  SNAPSHOT_EVENTS_FRAMEWORK_REDIS_URL: ""
#  SNAPSHOT_EVENTS_FRAMEWORK_ENV_NAMESPACE: ""
#  MONGODB_SSL_ENABLED_PIPELINE_SNAPSHOT: ""
#  DATABASE_INCLUDE_LIST_PIPELINE_SNAPSHOT: ""
#  COLLECTION_INCLUDE_LIST_PIPELINE_SNAPSHOT: ""
#  REDIS_STREAM_SIZE_PIPELINE_SNAPSHOT: ""
#  FIELD_EXCLUDE_LIST_PIPELINE_SNAPSHOT: ""
#  MONGODB_CONNECTION_STRING_PIPELINE_SNAPSHOT: ""

  IS_ENABLED_PLG: false
  #TODO: Set these values when IS_ENABLED_PLG is set to true.
#  MONGODB_SSL_ENABLED_PLG: ""
#  COLLECTION_INCLUDE_LIST_PLG: ""
#  DEBEZIUM_NAME_PLG: ""
#  MONGODB_NAME_PLG: ""
#  DATABASE_INCLUDE_LIST_PLG: ""
#  REDIS_STREAM_SIZE_PLG: ""
#  SNAPSHOT_MODE_PLG: ""
#  MAX_QUEUE_SIZE_PLG: ""
#  MAX_BATCH_SIZE_PLG: ""
#  MAX_QUEUE_SIZE_IN_BYTES_PLG: ""
#  POLL_INTERVAL_MS_PLG: ""
#  MONGODB_CONNECTION_STRING_PLG: ""

  IS_ENABLED_SSCA: false
  #TODO: Set these values when IS_ENABLED_SSCA is set to true.
#  MONGODB_SSL_ENABLED_SSCA: ""
#  COLLECTION_INCLUDE_LIST_SSCA: ""
#  DEBEZIUM_NAME_SSCA: ""
#  MONGODB_NAME_SSCA: ""
#  DATABASE_INCLUDE_LIST_SSCA: ""
#  REDIS_STREAM_SIZE_SSCA: ""
#  SNAPSHOT_MODE_SSCA: ""
#  MAX_QUEUE_SIZE_SSCA: ""
#  MAX_BATCH_SIZE_SSCA: ""
#  MAX_QUEUE_SIZE_IN_BYTES_SSCA: ""
#  POLL_INTERVAL_MS_SSCA: ""
#  MONGODB_CONNECTION_STRING_SSCA: ""
