apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ci-manager
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: "50%"
  selector:
    matchLabels:
    {{- include "ci-manager.selectorLabels" . | nindent 6 }}
