{{- if and .Values.global.monitoring.enabled (eq (lower .Values.global.monitoring.managedPlatform) "google") -}}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: ci-manager
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: ci-manager
  endpoints:
    - port: 8889
      interval: 120s
      path: "/api/ng-migration/metrics"
{{- end }}