DOCKER_FILE_PATH: /harness/harness-core/srm-service/build/container/Dockerfile-cv-nextgen-cie-jdk-multistage
CONTEXT_PATH: /harness/harness-core
HELM_CHART_SOURCE_DIRECTORY: harness-core/srm-service/chart

