DOCKER_FILE_PATH: /harness/harness-core/dockerization/event-server/Dockerfile-event-server-multistage-cie-jdk
CONTEXT_PATH: /harness/harness-core
HELM_CHART_SOURCE_DIRECTORY: harness-core/350-event-server/chart
