{{- if .Values.global.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: platform-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.virtualService.annotations }}
    {{- include "harnesscommon.tplvalues.render" (dict "value" .Values.virtualService.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  gateways:
    {{- if .Values.global.istio.gateway.create }}
    - istio-system/public
    {{- else }}
    {{- range .Values.global.istio.virtualService.gateways }}
    - {{ . }}
    {{- end }}
    {{- end }}
  hosts:
    {{- range .Values.global.istio.virtualService.hosts }}
    - {{ . }}
    {{- end }}
  http:
  - name: notification-service
    match:
    - uri:
        prefix: /notifications/
    - uri:
        prefix: /notifications
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 9005
        host: platform-service

  - name: audit-service
    match:
    - uri:
        prefix: /audit/
    - uri:
        prefix: /audit
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 9005
        host: platform-service

  - name: resourcegroup-service
    match:
    - uri:
        prefix: /resourcegroup/
    - uri:
        prefix: /resourcegroup
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 9005
        host: platform-service
{{ end }}