DOCKER_FILE_PATH: /harness/harness-core/dockerization/verification/Dockerfile-verification-cie-multistage-jdk
CONTEXT_PATH: /harness/harness-core
HELM_CHART_SOURCE_DIRECTORY: harness-core/270-verification/chart
