mongo:
  uri: mongodb://localhost:27017/assessment-harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  socketTimeout: 360000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO
  transactionsEnabled: false
  aliasDBName: assessment-harness
  traceMode: DISABLED
  maxOperationTimeInMillis: 300000

# change the ports
server:
  applicationConnectors:
    - type: http
      port: 12050
      maxRequestHeaderSize: 100KiB
  requestLog:
    appenders: []
  maxThreads: 1024

logging:
  level: INFO
  loggers:
    org.glassfish.jersey: WARN
    allbegray.slack: WARN
    org.glassfish.jersey.server.ServerRuntime.Responder: "OFF"
  appenders:
    - type: console
      threshold: TRACE
      target: STDOUT
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %cyan(%logger) - %msg %yellow(%replace(%mdc){'(.+)', '[$1]'}) %n"

  smtp:
    type: SMTP
    host: host_placeholder
    port: 465
    fromAddress: noreply@harness.io
    useSSL: true
    username: smtp_username_placeholder
    password: "smtp_password_placeholder"

baseUrl: "http://localhost:12050/"