pipeline_stages:
  - "stages/custom/custom-stage-node.yaml"
  - "stages/approval/approval-stage-node.yaml"
  - "stages/cd/deployment-stage-node.yaml"
  - "stages/ci/integration-stage-node.yaml"
  - "stages/pie/pipeline-stage-node.yaml"
  - "stages/security/security-stage-node.yaml"

custom_stage_steps:
  - "steps/wait_step.yaml"
  - "steps/http_step.yaml"
  - "template_node.yaml"