# Copyright 2021 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.
server:
  applicationConnectors:
    - type: https
      port: ${SERVER_APP_HTTPS_PORT:-7171}
      keyStorePath: keystore.jks
      keyStorePassword: password
      trustStorePath: ${JAVA_HOME}/lib/security/cacerts
      certAlias: localhost
      validateCerts: false
      maxRequestHeaderSize: 100KiB
    - type: http
      port: ${SERVER_APP_HTTP_PORT:-4457}
      maxRequestHeaderSize: 100KiB
  adminConnectors:
    - type: https
      port: ${SERVER_ADMIN_HTTPS_PORT:-7071}
      keyStorePath: keystore.jks
      keyStorePassword: password
      trustStorePath: ${JAVA_HOME}/lib/security/cacerts
      certAlias: localhost
      validateCerts: false
  requestLog:
    appenders: []

logging:
  level: INFO
  loggers:
    org.glassfish.jersey: WARN
    allbegray.slack: WARN
    org.glassfish.jersey.server.ServerRuntime.Responder: "OFF"
  appenders:
    - type: console
      threshold: TRACE
      target: STDOUT
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %cyan(%logger) - %msg %yellow(%replace(%mdc){'(.+)', '[$1]'}) %n"
    - type: gke-console
      threshold: TRACE
      target: STDOUT
      stackdriverLogEnabled: false

accessControlClient:
  enableAccessControl: false
  accessControlServiceConfig:
    baseUrl: http://localhost:9006/api/
    connectTimeOutSeconds: 15
    readTimeOutSeconds: 15
  accessControlServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM


redisLockConfig:
  sentinel: false
  masterName: "test"
  redisUrl: "redis://localhost:6379"
  sentinelUrls:
    - "redis://redis1:26379"
    - "redis://redis2:26379"
    - "redis://redis3:26379"
  envNamespace: ""
  readMode: MASTER
  nettyThreads: 16
  useScriptCache: true
  userName: ""
  password: ""

distributedLockImplementation: MONGO


harness-mongo:
  uri: mongodb://localhost:27018,127.0.0.1:27019,127.0.0.1:27017/harness?replicaSet=rs0
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  socketTimeout: 360000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 50
  aliasDBName: harness
cimanager-mongo:
  uri: mongodb://localhost:27018,127.0.0.1:27019,127.0.0.1:27017/harnessci?replicaSet=rs0
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  socketTimeout: 360000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO
  aliasDBName: harnessci
pmsMongo:
  uri: mongodb://localhost:27017/pms-harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  socketTimeout: 360000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO
  aliasDBName: pms-harness

enableAuth: false

scmConnectionConfig:
  url: localhost:8091

logServiceConfig:
  internalUrl: ""
  baseUrl: https://qa.harness.io/log-service/
  globalToken: "c76e567a-b341-404d-a8dd-d9738714eb82"

tiServiceConfig:
  internalUrl: ""
  baseUrl: http://localhost:8078
  globalToken: "78d16b66-4b4c-11eb-8377-acde48001122"

stoServiceConfig:
  baseUrl: http://localhost:4000
  globalToken: "551715ea-ca71-11ec-9d64-0242ac120002"

iacmServiceConfig:
  baseUrl: http://localhost:4000
  globalToken: "551715ea-ca71-11ec-9d64-0242ac120002"

managerTarget: localhost:9880
managerAuthority: localhost
managerServiceSecret: "IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM"
jwtAuthSecret: "dOkdsVqdRPPRJG31XU0qY4MPqmBBMk0PTAGIKM6O7TGqhjyxScIdJe80mwh5Yb5zF3KxYBHw6B3Lfzlq"
ngManagerServiceSecret: "IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM"
jwtIdentityServiceSecret: "HVSKUYqD4e5Rxu12hFDdCJKGM64sxgEynvdDhaOHaTHhwwn0K4Ttr0uoOxSsEVYNrUU="

ngManagerClientConfig:
  baseUrl: http://localhost:7457/
  connectTimeOutSeconds: 40
  readTimeOutSeconds: 40

managerClientConfig:
  baseUrl: http://localhost:3457/api/
  connectTimeOutSeconds: 15
  readTimeOutSeconds: 15
ciExecutionServiceConfig:
  miningPatternConfig:
    gcsCreds: null
    projectId: null
    bucketName: null
  queueServiceClient:
    queueServiceConfig:
      baseUrl: http://localhost:9091/
      connectTimeOutSeconds: 15
      readTimeOutSeconds: 15
    authToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiU0VSVklDRSIsIm5hbWUiOiJIU1FTIiwiZW1haWwiOiIiLCJ1c2VybmFtZSI6IiIsImlzcyI6Ikhhcm5lc3MgSW5jIiwiZXhwIjoxNjY5MjE5ODUxLCJuYmYiOjE2NjkyMTI2NTEsImlhdCI6MTY2OTIxMjY1MX0.TpxXD9jNv0tBywmgDQj1alDrXJGz-PTgerLkkBJDlAE
  addonImageTag: releaseBuild-30
  liteEngineImageTag: releaseBuild-29
  defaultMemoryLimit: 500
  defaultCPULimit: 400
  defaultInternalImageConnector: ''
  executionLimits:
    free:
      defaultTotalExecutionCount: 20
      defaultMacExecutionCount: 5
    team:
      defaultTotalExecutionCount: 50
      defaultMacExecutionCount: 10
    enterprise:
      defaultTotalExecutionCount: 100
      defaultMacExecutionCount: 10
    overrideConfig:
      - "kmpySmUISimoRrJL6NL73w:1:1"
  pvcDefaultStorageSize: 25600
  delegateServiceEndpointVariableValue: "2.tcp.ngrok.io:16426"
  addonImage: harness/ci-addon:1.16.4
  liteEngineImage: harness/ci-lite-engine:1.16.4
  isLocal: true
  remoteDebugTimeout: 3600
  cacheIntelligenceConfig:
    bucket: "gcp_bucket"
    serviceKey: "gcp_service_key"
  hostedVmConfig:
    splitLinuxAmd64Pool: false
    splitLinuxArm64Pool: false
    splitWindowsAmd64Pool: false
  stoStepConfig:
    defaultTag: ${STO_STEP_CONFIG_DEFAULT_TAG:-latest}
    defaultEntrypoint:
      - /bin/start.sh
      - "--run-strategy"
      - single-container
    images:
      - product: aquatrivy_default
        image: harness/aqua-trivy-job-runner
      - product: bandit_default
        image: harness/bandit-job-runner
      - product: blackduck_default
        image: harness/blackduckhub-job-runner
      - product: grype_default
        image: harness/grype-job-runner
      - product: snyk_default
        image: harness/snyk-job-runner
      - product: sonarqube_default
        image: harness/sonarqube-agent-job-runner
      - product: prismacloud_default
        image: harness/twistlock-job-runner
      - product: checkmarx_default
        image: harness/checkmarx-job-runner
      - product: zap_default
        image: harness/zap-job-runner
      - product: zap_quick
        image: harness/zap-job-runner
      - product: zap_attack
        image: harness/zap-job-runner
      - product: zap_standard
        image: harness/zap-job-runner
      - product: mend_default
        image: harness/whitesource-agent-job-runner
  stepConfig:
    # The below config is for K8 steps
    gitCloneConfig:
      # Use rootless image only for K8 git clone
      image: harness/drone-git:1.2.7-rootless
      entrypoint:
        - /usr/local/bin/clone
      windowsEntrypoint:
        - "pwsh"
        - "C:\\bin\\clone.ps1"
    buildAndPushDockerRegistryConfig:
      image: plugins/kaniko:1.7.0
      entrypoint:
        - /kaniko/kaniko-docker
    buildAndPushECRConfig:
      image: plugins/kaniko-ecr:1.7.0
      entrypoint:
        - /kaniko/kaniko-ecr
    buildAndPushGCRConfig:
      image: plugins/kaniko-gcr:1.7.0
      entrypoint:
        - /kaniko/kaniko-gcr
    buildAndPushACRConfig:
      image: plugins/kaniko-acr:1.7.0
      entrypoint:
        - /kaniko/kaniko-acr
    gcsUploadConfig:
      image: plugins/gcs:1.3.0
      entrypoint:
        - /bin/drone-gcs
      windowsEntrypoint:
        - "C:\\drone-gcs.exe"
    s3UploadConfig:
      image: plugins/s3:1.2.0
      entrypoint:
        - /bin/drone-s3
      windowsEntrypoint:
        - "C:\\drone-s3.exe"
    securityConfig:
      image: harness/sto-plugin:dev
      entrypoint:
        - /bin/sh
        - -c
        - python3 ${DOCKER_ENTRYPOINT}
    artifactoryUploadConfig:
      image: plugins/artifactory:1.2.0
      entrypoint:
        - /bin/plugin
      windowsEntrypoint:
        - "C:\\bin\\drone-artifactory.exe"
    cacheGCSConfig:
      image: plugins/cache:1.4.6
      entrypoint:
        - /bin/drone-cache
      windowsEntrypoint:
        - "C:\\drone-cache.exe"
    cacheS3Config:
      image: plugins/cache:1.4.6
      entrypoint:
        - /bin/drone-cache
      windowsEntrypoint:
        - "C:\\drone-cache.exe"
    vmImageConfig:
      # Use root image for VM git clone
      gitClone: harness/drone-git:1.2.7
      buildAndPushDockerRegistry: plugins/docker:20.13.0
      buildAndPushACR: plugins/acr:20.13.0
      buildAndPushECR: plugins/ecr:20.13.0
      buildAndPushGCR: plugins/gcr:20.13.0
      gcsUpload: plugins/gcs:1.3.0
      s3Upload: plugins/s3:1.2.0
      security: harness/sto-plugin:dev
      artifactoryUpload: plugins/artifactory:1.2.0
      cacheGCS: plugins/cache:1.4.6
      cacheS3: plugins/cache:1.4.6

pmsSdkExecutionPoolConfig:
  corePoolSize: ${PMS_SDK_EXECUTION_POOL_CORE_SIZE:-50}
  maxPoolSize: ${PMS_SDK_EXECUTION_POOL_MAX_SIZE:-300}
  idleTime: ${PMS_SDK_EXECUTION_POOL_IDLE_TIME:-120}
  timeUnit: ${PMS_SDK_EXECUTION_POOL_IDLE_TIME_TIME_UNIT:-SECONDS}

pmsSdkOrchestrationEventPoolConfig:
  corePoolSize: ${PMS_SDK_ORCHESTRATION_EVENT_POOL_CORE_SIZE:-50}
  maxPoolSize: ${PMS_SDK_ORCHESTRATION_EVENT_POOL_MAX_SIZE:-300}
  idleTime: ${PMS_SDK_ORCHESTRATION_EVENT_POOL_IDLE_TIME:-120}
  timeUnit: ${PMS_SDK_ORCHESTRATION_EVENT_POOL_IDLE_TIME_TIME_UNIT:-SECONDS}

asyncDelegateResponseConsumption:
  corePoolSize: ${ASYNC_DELEGATE_RESPONSE_THREAD_COUNT:-1}

pmsSdkGrpcServerConfig:
  connectors:
    - port: ${PMS_SDK_SERVER_CONFIG_SECURE_PORT:-12301}
      secure: true
      keyFilePath: key.pem
      certFilePath: cert.pem
    - port: ${PMS_SDK_SERVER_CONFIG_PORT:-12302}

pmsGrpcClientConfig:
  target: localhost:12011
  authority: localhost

apiUrl: https://localhost:8181/#/

shouldConfigureWithPMS: ${SHOULD_CONFIGURE_WITH_PMS:-true}

enableDashboardTimescale: false

timescaledb:
  timescaledbUrl: "jdbc:postgresql://localhost:5432/harness"
  timescaledbUsername: "postgres"
  timescaledbPassword: ""
  connectTimeout: 10
  socketTimeout: 30
  logUnclosedConnections: false
  loggerLevel: OFF

eventsFramework:
  redis:
    sentinel: false
    masterName: "test"
    redisUrl: "redis://localhost:6379"
    sentinelUrls:
      - "redis://redis1:26379"
      - "redis://redis2:26379"
      - "redis://redis3:26379"
    envNamespace: ""
    readMode: MASTER
    nettyThreads: 16
    useScriptCache: true
    userName: ""
    password: ""
    sslConfig:
      enabled: false
      CATrustStorePath: "/tmp/ca_trust_store"
      CATrustStorePassword: ""

hostname: ${HOSTNAME:-localhost}

basePathPrefix: ${BASE_PATH_PREFIX:-""}

segmentConfiguration:
  enabled: false
  url: "segment_url_place_holder"
  apiKey: "segment_api_key"
  certValidationRequired: false

cacheConfig:
  cacheBackend: REDIS
  cacheNamespace: ""
  disabledCaches: [ ]
  enterpriseCacheEnabled: true

enforcementClientConfiguration:
  enforcementCheckEnabled: false

pmsPlanCreatorServicePoolConfig:
  corePoolSize: ${PLAN_CREATOR_SERVICE_EXECUTOR_POOL_CORE_SIZE:-2}
  maxPoolSize: ${PLAN_CREATOR_SERVICE_EXECUTOR_POOL_MAX_SIZE:-3}
  idleTime: ${PLAN_CREATOR_SERVICE_EXECUTOR_POOL_IDLE_TIME:-30}
  timeUnit: ${PLAN_CREATOR_SERVICE_EXECUTOR_POOL_IDLE_TIME_TIME_UNIT:-SECONDS}

enableOpentelemetry: false