# Dropwizard config
server:
  allowedMethods: ["GET"]
  adminConnectors: []
  applicationConnectors:
    - type: http
      port: 3460
      maxRequestHeaderSize: 100KiB
  rootPath: /api
  maxThreads: 1024

logging:
  type: external

# Delegate Config
accountId: px7xd_BFRCi-pfWPYXVjvw
delegateToken: a8f795667549c2296fd8c719084d4f8d
managerUrl: https://qa.harness.io/api/
verificationServiceUrl: https://qa.harness.io/verification/
cvNextGenUrl: https://qa.harness.io/cv/api/
logStreamingServiceBaseUrl: https://qa.harness.io/log-service/
heartbeatIntervalMs: 50000
localDiskPath: /tmp
doUpgrade: false
pollForTasks: false
description: description here
managerTarget: localhost:9880
managerAuthority: localhost
queueFilePath: ../eventQueue
grpcServiceEnabled: true
grpcServiceConnectorPort: 8080
clientToolsDownloadDisabled: true
installClientToolsInBackground: true

# Required for local development as manger uses self-signed cert
trustAllCertificates: true