mongo:
  uri: mongodb://localhost:27017/idp-harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  socketTimeout: 360000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO
  transactionsEnabled: false
  aliasDBName: idp-harness
  traceMode: DISABLED
  maxOperationTimeInMillis: 300000