apiVersion: v1
kind: Secret
metadata:
  name: access-control
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "access-control.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "access-control.generateSecrets" . }}