mongo:
  uri: mongodb://localhost:27017/harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  socketTimeout: 360000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO
  traceMode: DISABLED
  mongoSSLConfig:
    mongoSSLEnabled: false
    mongoTrustStorePath:
    mongoTrustStorePassword:
  aliasDBName: harness