integrations:
  github:
    - host: HOST_VALUE
      apiBaseUrl: API_BASE_URL
      apps:
        - appId: ${HARNESS_GITHUB_APP_APPLICATION_ID}
          clientId: dummy
          clientSecret: dummy
          webhookSecret: dummy
          privateKey: |
            ${HARNESS_GITHUB_APP_PRIVATE_KEY_REF}

