BUILD_SCRIPT_PATH="access-control/build/feature_build.sh"
DOCKER_FILE_PATH="/harness/dist/accesscontrol-service/Dockerfile-cie-jdk"
CONTEXT_PATH="/harness/dist/accesscontrol-service"
ARTIFACT_REPO="harness/feature-accesscontrol-service-openjdk-8u242"
HELM_CHART_REPO="access-control/chart"
HELM_PUBLISH_REPO="us-west1-docker.pkg.dev/platform-205701/harness-helm-artifacts"
BUILD_STEP_RESOURCE_CPU="5000m"
BUILD_STEP_RESOURCE_MEMORY="15Gi"