DOCKER_FILE_PATH: /harness/harness-core/access-control/build/container/Dockerfile-accesscontrol-service-cie-jdk-multistage
CONTEXT_PATH: /harness/harness-core
HELM_CHART_SOURCE_DIRECTORY: harness-core/access-control/chart