apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  CACHE_BACKEND: {{ .Values.config.CACHE_BACKEND | default 'REDIS' }}
  CACHE_CONFIG_REDIS_SENTINELS: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  CACHE_CONFIG_SENTINEL_MASTER_NAME: {{ .Values.config.CACHE_CONFIG_SENTINEL_MASTER_NAME | default 'harness-redis' }}
  CACHE_CONFIG_USE_SENTINEL: {{ .Values.global.database.redis.installed | quote }}
  CACHE_CONFIG_REDIS_URL: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  DEPLOY_MODE: {{ .Values.config.DEPLOY_MODE | default 'KUBERNETES_ONPREM' }}
  LOGGING_LEVEL: {{ .Values.appLogLevel }}
  LOCK_CONFIG_REDIS_SENTINELS: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  LOCK_CONFIG_SENTINEL_MASTER_NAME: {{ .Values.config.LOCK_CONFIG_SENTINEL_MASTER_NAME | default 'harness-redis' }}
  LOCK_CONFIG_USE_SENTINEL: {{ .Values.global.database.redis.installed | quote }}
  LOCK_CONFIG_REDIS_URL: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  STACK_DRIVER_LOGGING_ENABLED: {{ .Values.global.stackDriverLoggingEnabled | quote }}
  MEMORY: {{ .Values.java.memory | quote }}
  MANAGER_TARGET: {{ .Values.config.MANAGER_TARGET | default 'harness-manager:9879' }}
  MANAGER_AUTHORITY: {{ .Values.config.MANAGER_AUTHORITY | default 'harness-manager:9879' }}
  GRPC_SERVER_PORT: {{ .Values.config.GRPC_SERVER_PORT | default '12011' }}
  NG_MANAGER_TARGET: {{ .Values.config.NG_MANAGER_TARGET | default 'ng-manager:9979' }}
  NG_MANAGER_AUTHORITY: {{ .Values.config.NG_MANAGER_AUTHORITY | default 'ng-manager:9979' }}
  NG_MANAGER_GITSYNC_TARGET: {{ .Values.config.NG_MANAGER_GITSYNC_TARGET | default 'ng-manager:13002' }}
  NG_MANAGER_GITSYNC_AUTHORITY: {{ .Values.config.NG_MANAGER_GITSYNC_AUTHORITY | default 'ng-manager:13002' }}
  CI_MANAGER_TARGET: {{ .Values.config.CI_MANAGER_TARGET | default 'ci-manager:9979' }}
  CI_MANAGER_AUTHORITY: {{ .Values.config.CI_MANAGER_AUTHORITY | default 'ci-manager:9979' }}
  SCM_SERVICE_URI: {{ .Values.config.SCM_SERVICE_URI | default 'scm-service:8091' }}
  EVENTS_FRAMEWORK_REDIS_URL: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  EVENTS_FRAMEWORK_USE_SENTINEL: {{ .Values.global.database.redis.installed | quote }}
  EVENTS_FRAMEWORK_SENTINEL_MASTER_NAME: {{ .Values.config.EVENTS_FRAMEWORK_SENTINEL_MASTER_NAME | default 'harness-redis' }}
  EVENTS_FRAMEWORK_REDIS_SENTINELS: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  PIPELINE_SERVICE_BASE_URL: '{{ .Values.global.loadbalancerURL }}/ng/#'
  PMS_API_BASE_URL: '{{ .Values.global.loadbalancerURL }}/gateway/pipeline/api/'
  LOG_STREAMING_SERVICE_BASEURL: 'http://log-service.{{ .Release.Namespace }}.svc.cluster.local:8079/'
  MANAGER_BASE_URL: {{ .Values.config.MANAGER_BASE_URL | default 'http://harness-manager:9090/api/' }}
  NG_MANAGER_BASE_URL: {{ .Values.config.NG_MANAGER_BASE_URL | default 'http://ng-manager:7090/' }}
  WEBHOOK_TRIGGER_BASEURL: '{{ .Values.global.loadbalancerURL }}/ng/api/'
  CUSTOM_TRIGGER_BASEURL: '{{ .Values.global.loadbalancerURL }}/gateway/pipeline/api/'
  ACCESS_CONTROL_BASE_URL: {{ .Values.config.ACCESS_CONTROL_BASE_URL | default 'http://access-control:9006/api/' }}
  NOTIFICATION_BASE_URL: {{ .Values.config.NOTIFICATION_BASE_URL | default 'http://platform-service:9005/api/' }}
  TEMPLATE_SERVICE_ENDPOINT: {{ .Values.config.TEMPLATE_SERVICE_ENDPOINT | default 'http://template-service:15002/api/' }}
  CI_MANAGER_BASE_URL: {{ .Values.config.CI_MANAGER_BASE_URL | default 'http://ci-manager:7090/' }}
  MANAGER_CLIENT_BASEURL: {{ .Values.config.MANAGER_CLIENT_BASEURL | default 'http://harness-manager:9090/api/' }}
  AUTH_ENABLED: {{ .Values.config.AUTH_ENABLED | default 'true' }}
  USE_REDIS_FOR_INTERRUPTS: {{ .Values.config.USE_REDIS_FOR_INTERRUPTS | default 'true' }}
  USE_REDIS_FOR_ORCHESTRATION_EVENTS: {{ .Values.config.USE_REDIS_FOR_ORCHESTRATION_EVENTS | default 'true' }}
  USE_REDIS_FOR_SDK_RESPONSE_EVENTS: {{ .Values.config.USE_REDIS_FOR_SDK_RESPONSE_EVENTS | default 'true' }}
  MOCK_ACCESS_CONTROL_SERVICE: {{ .Values.config.MOCK_ACCESS_CONTROL_SERVICE | default 'false' }}
  ACCESS_CONTROL_ENABLED: {{ .Values.config.ACCESS_CONTROL_ENABLED | default 'true' }}
  ENABLE_DASHBOARD_TIMESCALE: {{ .Values.config.ENABLE_DASHBOARD_TIMESCALE | default 'true' }}
  SHOULD_USE_INSTANCE_CACHE: {{ .Values.config.SHOULD_USE_INSTANCE_CACHE | default 'false' }}
  STO_MANAGER_BASE_URL: {{ .Values.config.STO_MANAGER_BASE_URL | default 'http://sto-manager:7090/' }}
  STO_MANAGER_AUTHORITY: {{ .Values.config.STO_MANAGER_AUTHORITY | default 'sto-manager:9979' }}
  STO_MANAGER_TARGET: {{ .Values.config.STO_MANAGER_TARGET | default 'sto-manager:9979' }}
  CV_MANAGER_BASE_URL: {{ .Values.config.CV_MANAGER_BASE_URL | default 'http://cv-nextgen:6060/cv/api/' }}
  CVNG_MANAGER_AUTHORITY: {{ .Values.config.CVNG_MANAGER_AUTHORITY | default 'cv-nextgen:9979' }}
  CVNG_MANAGER_TARGET: {{ .Values.config.CVNG_MANAGER_TARGET | default 'cv-nextgen:9979' }}
  {{- if .Values.global.opa.enabled }}
  OPA_SERVER_BASEURL: 'http://policy-mgmt.{{ .Release.Namespace }}.svc.cluster.local:3000/'
  {{- end }}
  ENABLE_AUDIT: {{ .Values.config.ENABLE_AUDIT | default 'true' }}
  AUDIT_SERVICE_BASE_URL: {{ .Values.config.AUDIT_SERVICE_BASE_URL | default 'http://platform-service:9005/api/' }}
  DISABLE_FREEZE_NOTIFY_TEMPLATE: '{{ .Values.global.disableFreezeNotifyTemplate }}'
  LOG_STREAMING_CONTAINER_STEP_BASE_URL: '{{ .Values.global.loadbalancerURL }}/log-service/'
  ALLOWED_ORIGINS: '{{ .Values.allowedOrigins | default .Values.global.loadbalancerURL }}'
  {{- if .Values.global.ssca.enabled }}
  SSCA_MANAGER_ENABLED: {{ .Values.config.SSCA_MANAGER_ENABLED | default 'true' }}
  SSCA_SERVICE_ENDPOINT: '{{ .Values.global.loadbalancerURL }}/ssca-manager/'
  SSCA_ORCHESTRATION_IMAGE: '{{ .Values.ssca_images.ssca_plugin.image.repository }}:{{ .Values.ssca_images.ssca_plugin.image.tag }}'
  SSCA_ENFORCEMENT_IMAGE: '{{ .Values.ssca_images.ssca_plugin.image.repository }}:{{ .Values.ssca_images.ssca_plugin.image.tag }}'
  {{- end }}
  {{ include "harnesscommon.harnessfunctions.java17flags" (dict "context" $) | nindent 2 }}
  {{- if .Values.additionalConfigs }}
  {{- toYaml .Values.additionalConfigs | nindent 2 }}
  {{- end }}
  {{- include "harnesscommon.monitoring.config" . | nindent 2 }}
