{{- if and .Values.global.monitoring.enabled (eq (lower .Values.global.monitoring.managedPlatform) "google") -}}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: pipeline-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: pipeline-service
  endpoints:
    - port: 8889
      interval: 120s
      path: "/metrics"

{{- end }}