proxy:
  '/harness/stress':
    target: 'https://stress.harness.io/'
    pathRewrite:
      '/api/proxy/harness/stress/?': '/'
    allowedHeaders:
      - authorization
  '/harness/scorecard':
    target: 'https://stress.harness.io/'
    pathRewrite:
      '/api/proxy/harness/scorecard/?': '/'
    allowedHeaders:
      - authorization
      - Harness-Account