proxy:
  '/harness/prod':
    target: 'https://app3.harness.io/'
    pathRewrite:
      '/api/proxy/harness/prod/?': '/'
    allowedHeaders:
      - authorization
  '/harness/scorecard':
    target: 'https://app3.harness.io/'
    pathRewrite:
      '/api/proxy/harness/scorecard/?': '/'
    allowedHeaders:
      - authorization
      - Harness-Account