proxy:
  '/harness/qa':
    target: 'https://qa.harness.io/'
    pathRewrite:
      '/api/proxy/harness/qa/?': '/'
    allowedHeaders:
      - authorization
  '/harness/scorecard':
    target: 'https://qa.harness.io/'
    pathRewrite:
      '/api/proxy/harness/scorecard/?': '/'
    allowedHeaders:
      - authorization
      - Harness-Account