BUILD_SCRIPT_PATH="840-template-service/build/feature_build.sh"
DOCKER_FILE_PATH="/harness/harness-core/dist/template-service/Dockerfile-cie-jdk"
CONTEXT_PATH="/harness/harness-core/dist/template-service"
ARTIFACT_REPO="harness/feature-template-service-openjdk-8u242"
HELM_CHART_SOURCE_DIRECTORY="harness-core/840-template-service/chart"
HELM_REPO_NAME="us-west1-docker.pkg.dev/platform-205701/harness-helm-artifacts"
BUILD_STEP_RESOURCE_CPU="1000m"
BUILD_STEP_RESOURCE_MEMORY="4Gi"