apiVersion: v1
kind: ConfigMap
metadata:
  name: sto-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  DEPLOY_MODE: {{ .Values.config.DEPLOY_MODE | default 'KUBERNETES_ONPREM' }}
  ADDON_IMAGE: '{{ .Values.addOnImage.image.repository }}:{{ .Values.addOnImage.image.tag }}'
  LE_IMAGE: '{{ .Values.leImage.image.repository }}:{{ .Values.leImage.image.tag }}'
  MEMORY: {{ .Values.java.memory | quote }}
  MANAGER_TARGET: {{ .Values.config.MANAGER_TARGET | default 'harness-manager:9879' }}
  MANAGER_AUTHORITY: {{ .Values.config.MANAGER_AUTHORITY | default 'harness-manager:9879' }}
  MANAGER_URL: 'http://harness-manager.{{ .Release.Namespace }}.svc.cluster.local:9090/api/'
  SCM_SERVICE_URI: {{ .Values.config.SCM_SERVICE_URI | default 'scm-service:8091' }}
  LOG_SERVICE_ENDPOINT: '{{ .Values.global.loadbalancerURL }}/gateway/log-service/'
  LOG_SERVICE_INTERNAL_URL: 'http://log-service.{{ .Release.Namespace }}.svc.cluster.local:8079/'
  TI_SERVICE_ENDPOINT: '{{ .Values.global.loadbalancerURL }}/ti-service/'
  TI_SERVICE_INTERNAL_ENDPOINT: 'http://ti-service.{{ .Release.Namespace }}.svc.cluster.local:8078/'
  STO_SERVICE_ENDPOINT:  '{{ .Values.global.loadbalancerURL }}/sto/'
  STO_SERVICE_INTERNAL_ENDPOINT: 'http://sto-core.{{ .Release.Namespace }}.svc.cluster.local:4000/'
  NG_MANAGER_URL: 'http://ng-manager.{{ .Release.Namespace }}.svc.cluster.local:7090/'
  ENABLE_APPDYNAMICS: {{ .Values.config.ENABLE_APPDYNAMICS | default 'false' }}
  DISABLE_NEW_RELIC: {{ .Values.config.DISABLE_NEW_RELIC | default 'true' }}
  SHOULD_CONFIGURE_WITH_PMS: {{ .Values.config.SHOULD_CONFIGURE_WITH_PMS | default 'true' }}
  PMS_TARGET: {{ .Values.config.PMS_TARGET | default 'pipeline-service:12011' }}
  PMS_AUTHORITY: {{ .Values.config.PMS_AUTHORITY | default 'pipeline-service:12011' }}
  GRPC_SERVER_PORT: {{ .Values.config.GRPC_SERVER_PORT | default '9979' }}
  DEFAULT_INTERNAL_IMAGE_CONNECTOR: {{ .Values.defaultInternalImageConnector }}
  API_URL: '{{ .Values.global.loadbalancerURL }}/ng/#/'
  DEFAULT_CPU_LIMIT: {{ .Values.config.DEFAULT_CPU_LIMIT | default '500' }}
  DEFAULT_MEMORY_LIMIT: {{ .Values.java.memoryLimit | quote }}
  MONGO_INDEX_MANAGER_MODE: {{ .Values.config.MONGO_INDEX_MANAGER_MODE | default 'AUTO' }}
  STACK_DRIVER_LOGGING_ENABLED: {{ .Values.global.stackDriverLoggingEnabled | quote }}
  GOOGLE_APPLICATION_CREDENTIALS: {{ .Values.config.GOOGLE_APPLICATION_CREDENTIALS | default '/opt/harness/svc/cloud_stackdriver.json' }}
  EVENTS_FRAMEWORK_USE_SENTINEL: {{ .Values.global.database.redis.installed | quote }}
  EVENTS_FRAMEWORK_SENTINEL_MASTER_NAME: {{ .Values.config.EVENTS_FRAMEWORK_SENTINEL_MASTER_NAME | default 'harness-redis' }}
  EVENTS_FRAMEWORK_REDIS_SENTINELS: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  EVENTS_FRAMEWORK_REDIS_URL: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  LOCK_CONFIG_USE_SENTINEL: {{ .Values.global.database.redis.installed | quote }}
  LOCK_CONFIG_SENTINEL_MASTER_NAME: {{ .Values.config.LOCK_CONFIG_SENTINEL_MASTER_NAME | default 'harness-redis' }}
  LOCK_CONFIG_REDIS_SENTINELS: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  LOCK_CONFIG_REDIS_URL: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  USE_REDIS_FOR_SDK_RESPONSE_EVENTS: {{ .Values.config.USE_REDIS_FOR_SDK_RESPONSE_EVENTS | default 'true' }}
  ENABLE_DASHBOARD_TIMESCALE: {{ .Values.config.ENABLE_DASHBOARD_TIMESCALE | default 'true' }}
  TIMESCALE_URI: 'jdbc:postgresql://timescaledb-single-chart.{{ .Release.Namespace }}:5432/harness'
  CACHE_BACKEND: {{ .Values.config.CACHE_BACKEND | default 'REDIS' }}
  CACHE_CONFIG_USE_SENTINEL: {{ .Values.global.database.redis.installed | quote }}
  CACHE_CONFIG_SENTINEL_MASTER_NAME: {{ .Values.config.CACHE_CONFIG_SENTINEL_MASTER_NAME | default 'harness-redis' }}
  CACHE_CONFIG_REDIS_SENTINELS: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  CACHE_CONFIG_REDIS_URL: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  {{- if .Values.scalabilityTest}}
  PLAN_CREATOR_SERVICE_EXECUTOR_POOL_CORE_SIZE: {{ .Values.config.PLAN_CREATOR_SERVICE_EXECUTOR_POOL_CORE_SIZE | default '150' }}
  PLAN_CREATOR_SERVICE_EXECUTOR_POOL_MAX_SIZE: {{ .Values.config.PLAN_CREATOR_SERVICE_EXECUTOR_POOL_MAX_SIZE | default '200' }}
  ASYNC_DELEGATE_RESPONSE_THREAD_COUNT: {{ .Values.config.ASYNC_DELEGATE_RESPONSE_THREAD_COUNT | default '15' }}
  {{- end}}
  ENFORCEMENT_CHECK_ENABLED: {{ .Values.config.ENFORCEMENT_CHECK_ENABLED | default 'false' }}
  PMS_SDK_ORCHESTRATION_EVENT_POOL_CORE_SIZE: {{ .Values.config.PMS_SDK_ORCHESTRATION_EVENT_POOL_CORE_SIZE | default '15' }}
  S3_UPLOAD_IMAGE: '{{ .Values.s3UploadImage.image.repository }}:{{ .Values.s3UploadImage.image.tag }}'
  USE_DMS: {{ .Values.config.USE_DMS | default 'false' }}
  SECURITY_IMAGE: '{{ .Values.securityImage.image.repository }}:{{ .Values.securityImage.image.tag }}'
  {{- if .Values.additionalConfigs }}
  {{- toYaml .Values.additionalConfigs | nindent 2 }}
  {{- end }}
  {{- if .Values.global.opa.enabled }}
  OPA_SERVER_BASEURL: 'http://policy-mgmt.{{ .Release.Namespace }}.svc.cluster.local:3000/'
  {{- end }}
  {{ include "harnesscommon.harnessfunctions.java17flags" (dict "context" $) | nindent 2 }}
