DOCKER_FILE_PATH: /harness/harness-core/debezium-service/build/container/Dockerfile-debezium-service-multistage
HELM_CHART_SOURCE_DIRECTORY: harness-core/debezium-service/chart
VERSION_FILE: harness-core/980-commons/src/main/resources-filtered/versionInfo.yaml


