---
# Source: ce-nextgen/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nextgen-ce
  namespace: default
  labels:
spec:
  minAvailable: "50%"
  selector:
   matchLabels:
    app: nextgen-ce
---
# Source: ce-nextgen/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: nextgen-ce
  namespace: default
  labels:
    helm.sh/chart: ce-nextgen-0.12.1
    app.kubernetes.io/name: nextgen-ce
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.81102"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:  
  AWS_ACCESS_KEY: "RG5wRmtRRWx2Zg=="
  AWS_SECRET_KEY: "ZlpKRmE3OHVYRQ=="
  AWS_ACCOUNT_ID: "cHFzc1M0Q1Q2dg=="
  AWS_DESTINATION_BUCKET: "VUFDTlpUMzJ6WA=="
  AWS_TEMPLATE_LINK: "SjEyOXBUZmRRQg=="
  CE_AWS_TEMPLATE_URL: "S1lPeFBZYXlBRQ=="
  AZURE_APP_CLIENT_SECRET: "QVFNUHhxcTlFaQ=="
  JWT_AUTH_SECRET: 'SUMwNExZTUJmMWxEUDVvZVk0aHVweGQ0SEpoTG1ONmF6VWt1M3hFYmVFM1NVeDVHM1pZemhiaXdWdEs0aTdBbXF5VTlPWmt3QjR2OEU5cU0='
  NEXT_GEN_MANAGER_SECRET: 'SUMwNExZTUJmMWxEUDVvZVk0aHVweGQ0SEpoTG1ONmF6VWt1M3hFYmVFM1NVeDVHM1pZemhiaXdWdEs0aTdBbXF5VTlPWmt3QjR2OEU5cU0='
  JWT_IDENTITY_SERVICE_SECRET: 'SFZTS1VZcUQ0ZTVSeHUxMmhGRGRDSktHTTY0c3hnRXludmREaGFPSGFUSGh3d24wSzRUdHIwdW9PeFNzRVZZTnJVVT0='
  NOTIFICATION_CLIENT_SECRET: 'SUMwNExZTUJmMWxEUDVvZVk0aHVweGQ0SEpoTG1ONmF6VWt1M3hFYmVFM1NVeDVHM1pZemhiaXdWdEs0aTdBbXF5VTlPWmt3QjR2OEU5cU0='
  ACCESS_CONTROL_SECRET: 'SUMwNExZTUJmMWxEUDVvZVk0aHVweGQ0SEpoTG1ONmF6VWt1M3hFYmVFM1NVeDVHM1pZemhiaXdWdEs0aTdBbXF5VTlPWmt3QjR2OEU5cU0='
---
# Source: ce-nextgen/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ceng-secret-mount
  namespace: default
  labels:
    helm.sh/chart: ce-nextgen-0.12.1
    app.kubernetes.io/name: nextgen-ce
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.81102"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
    ceng-gcp-credentials: "RHplUG9pdEpHcw=="
---
# Source: ce-nextgen/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextgen-ce
  namespace: default
  labels:
data:
  LOGGING_LEVEL: "INFO"
  MANAGER_TARGET: "harness-manager:9879"
  MANAGER_AUTHORITY: "harness-manager:9879"
  MANAGER_CLIENT_BASEURL: "http://harness-manager.default.svc.cluster.local:9090/api/"
  NG_MANAGER_CLIENT_BASEURL: "http://ng-manager.default.svc.cluster.local:7090/"
  MANAGER_URL: "http://harness-manager.default.svc.cluster.local:9090/api/"
  DEPLOY_MODE: "KUBERNETES_ONPREM"
  CE_NEXTGEN_PORT: "6340"
  EVENTS_FRAMEWORK_REDIS_URL: redis://redis-sentinel-harness-announce-0:26379,redis://redis-sentinel-harness-announce-1:26379,redis://redis-sentinel-harness-announce-2:26379
  EVENTS_FRAMEWORK_USE_SENTINEL: "true"
  EVENTS_FRAMEWORK_SENTINEL_MASTER_NAME: "harness-redis"
  EVENTS_FRAMEWORK_REDIS_SENTINELS: redis://redis-sentinel-harness-announce-0:26379,redis://redis-sentinel-harness-announce-1:26379,redis://redis-sentinel-harness-announce-2:26379
  EVENTS_FRAMEWORK_ENV_NAMESPACE: ""
  EVENTS_FRAMEWORK_REDIS_SSL_ENABLED: "false"
  LOCK_CONFIG_REDIS_URL: redis://redis-sentinel-harness-announce-0:26379,redis://redis-sentinel-harness-announce-1:26379,redis://redis-sentinel-harness-announce-2:26379
  LOCK_CONFIG_REDIS_SENTINELS: redis://redis-sentinel-harness-announce-0:26379,redis://redis-sentinel-harness-announce-1:26379,redis://redis-sentinel-harness-announce-2:26379
  LOCK_CONFIG_SENTINEL_MASTER_NAME: "harness-redis"
  LOCK_CONFIG_USE_SENTINEL: "true"
  GOOGLE_CREDENTIALS_PATH: "/opt/harness/svc/ceng_gcp_credentials.json"
  GOOGLE_APPLICATION_CREDENTIALS: "/opt/harness/svc/ceng_gcp_credentials.json"
  CE_GCP_CREDENTIALS_PATH: "/opt/harness/svc/ceng_gcp_credentials.json"
  STACK_DRIVER_LOGGING_ENABLED: "false"
  EVENTS_MONGO_INDEX_MANAGER_MODE: "AUTO"
  GCP_PROJECT_ID: "placeHolder"
  AZURE_APP_CLIENT_ID: "0211763d-24fb-4d63-865d-92f86f77e908"
  AZURE_ENABLE_FILE_CHECK_AT_SOURCE: "true"
  AWS_GOV_CLOUD_ACCOUNT_ID: "147449478367"
  AWS_GOV_CLOUD_TEMPLATE_LINK: "https://continuous-efficiency.s3.us-east-2.amazonaws.com/setup/v1/ng/HarnessAWSTemplate.yaml"
  AWS_GOV_CLOUD_REGION_NAME: "us-gov-west-1"
  SEGMENT_ENABLED: "false"
  AUDIT_ENABLED: "true"
  AUDIT_CLIENT_BASEURL: "http://platform-service.default.svc.cluster.local:9005/api/"
  NOTIFICATION_BASE_URL: "http://platform-service.default.svc.cluster.local:9005/api/"
  ACCESS_CONTROL_BASE_URL: "http://access-control.default.svc.cluster.local:9006/api/"
  ACCESS_CONTROL_ENABLED: "true"
  MOCK_ACCESS_CONTROL_SERVICE: "false"
  MEMORY: "4096m"
  ENABLE_APPDYNAMICS: "false"
  CLICKHOUSE_ENABLED: "false"
  DISTRIBUTED_LOCK_IMPLEMENTATION: "MONGO"
  USE_WORKLOAD_IDENTITY: "false"
  GCP_SERVICE_ACCOUNT_EMAIL: "placeHolder"
  
  JAVA_17_FLAGS: --illegal-access=debug --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens java.base/java.time=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.math=ALL-UNNAMED --add-opens java.base/java.nio.file=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED --add-opens java.xml/com.sun.org.apache.xpath.internal=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-exports java.xml/com.sun.org.apache.xerces.internal.parsers=ALL-UNNAMED --add-exports java.base/sun.nio.ch=ALL-UNNAMED
  ENABLE_PROMETHEUS_COLLECTOR: "false"
  PROMETHEUS_COLLECTOR_PORT: "8889"
---
# Source: ce-nextgen/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nextgen-ce
  namespace: default
  labels:
    helm.sh/chart: ce-nextgen-0.12.1
    app.kubernetes.io/name: nextgen-ce
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.81102"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 6340
      targetPort: 6340
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nextgen-ce
    app.kubernetes.io/instance: release-name
---
# Source: ce-nextgen/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextgen-ce
  namespace: default
  labels:
    helm.sh/chart: ce-nextgen-0.12.1
    app.kubernetes.io/name: nextgen-ce
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.81102"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: nextgen-ce
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app: nextgen-ce
        app.kubernetes.io/name: nextgen-ce
        app.kubernetes.io/instance: release-name
    spec:
      
      serviceAccountName: harness-default
      securityContext:
        {}
      initContainers:
    #waits only for mongo & timescale to start
      - name: wait-for-mongo
        image: docker.io/harness/helm-init-container:latest
        imagePullPolicy: IfNotPresent
        args:
          - "pod"
          - "-lapp=mongodb-replicaset"
      - name: wait-for-timescale
        image: docker.io/harness/helm-init-container:latest
        imagePullPolicy: IfNotPresent
        args:
          - "pod"
          - "-lapp=timescaledb-single-chart"
      containers:
        
        - name: nextgen-ce
          securityContext:            {}
          image: docker.io/harness/ce-nextgen-signed:81102-000
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /ccm/api/health
              port: 6340
            initialDelaySeconds: 30
            failureThreshold: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /ccm/api/health
              port: 6340
            initialDelaySeconds: 30
            failureThreshold: 10
            periodSeconds: 15
          envFrom:
            - configMapRef:
                name: nextgen-ce
          env:                        
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: harness-secrets
                  key: mongodbUsername
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-replicaset-chart
                  key: mongodb-root-password            
            - name: TIMESCALEDB_USERNAME
              value: postgres
            - name: TIMESCALEDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harness-secrets
                  key: timescaledbPostgresPassword            
            - name: JWT_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: nextgen-ce
                  key: JWT_AUTH_SECRET            
            - name: NEXT_GEN_MANAGER_SECRET
              valueFrom:
                secretKeyRef:
                  name: nextgen-ce
                  key: NEXT_GEN_MANAGER_SECRET            
            - name: JWT_IDENTITY_SERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: nextgen-ce
                  key: JWT_IDENTITY_SERVICE_SECRET            
            - name: NOTIFICATION_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nextgen-ce
                  key: NOTIFICATION_CLIENT_SECRET            
            - name: ACCESS_CONTROL_SECRET
              valueFrom:
                secretKeyRef:
                  name: nextgen-ce
                  key: ACCESS_CONTROL_SECRET
            - name: EVENTS_MONGO_DB_URL
              value: 'mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongodb-replicaset-chart-0.mongodb-replicaset-chart.default.svc/events?authSource=admin'
            - name: NOTIFICATION_MONGO_URI
              value: 'mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongodb-replicaset-chart-0.mongodb-replicaset-chart.default.svc/notifications?authSource=admin'
            - name: TIMESCALEDB_URI
              value: jdbc:postgresql://timescaledb-single-chart.default:5432/harness
          volumeMounts:
          - name: secret-mount
            mountPath: /opt/harness/svc
          resources:
            limits:
              memory: 4Gi
            requests:
              cpu: 1
              memory: 4Gi
      volumes:
      - name: secret-mount
        secret:
          secretName: ceng-secret-mount
          items:
          - key: ceng-gcp-credentials
            path: ceng_gcp_credentials.json
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nextgen-ce
            topologyKey: "kubernetes.io/hostname"
