apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-manager.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "harness-manager.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{.Values.maxSurge}}
      maxUnavailable: {{.Values.maxUnavailable}}
  template:
    metadata:
      annotations:
        {{- include "harnesscommon.monitoring.annotations" . | nindent 8 }}
        rollme: {{ randAlphaNum 5 | quote }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: harness-manager
        {{- include "harness-manager.selectorLabels" . | nindent 8 }}
        {{- if .Values.global.commonLabels }}
        {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.podLabels }}
        {{- include "harnesscommon.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "harness-manager.pullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "harness-manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      {{- if .Values.global.database.mongo.installed }}
      - name: wait-for-mongo
        image: {{ include "common.images.image" (dict "imageRoot" .Values.waitForInitContainer.image "global" .Values.global) }}
        imagePullPolicy: IfNotPresent
        args:
          - "pod"
          - "-lapp=mongodb-replicaset"
      {{- end }}
      {{- if .Values.global.database.timescaledb.installed }}
      - name: wait-for-timescale
        image: {{ include "common.images.image" (dict "imageRoot" .Values.waitForInitContainer.image "global" .Values.global) }}
        imagePullPolicy: IfNotPresent
        args:
          - "pod"
          - "-lapp=timescaledb-single-chart"
      {{- end }}
      {{- if .Values.global.database.redis.installed }}
      - name: wait-for-redis
        image: {{ include "common.images.image" (dict "imageRoot" .Values.waitForInitContainer.image "global" .Values.global) }}
        imagePullPolicy: IfNotPresent
        args:
          - "pod"
          - "-lapp=redis-sentinel"
      {{- end }}
      containers:
        - envFrom:
            - configMapRef:
                name: harness-manager-config
            {{- if .Values.global.smtpCreateSecret.enabled }}
            - secretRef:
                name: smtp-secret
            {{- end }}
          env:
            {{- if not .Values.global.database.redis.installed }}
            {{- include "harnesscommon.secrets.manageEnv" (dict "ctx" . "variableName" "REDIS_USERNAME" "kubernetesSecretName" .Values.global.database.redis.secretName "kubernetesSecretKey" .Values.global.database.redis.userKey "extKubernetesSecretCtxs" (list .Values.secrets.kubernetesSecrets .Values.global.database.redis.secrets.kubernetesSecrets) "esoSecretCtxs" (list (dict "secretCtxIdentifier" "local" "secretCtx" .Values.secrets.secretManagement.externalSecretsOperator) (dict "secretCtxIdentifier" "global" "secretCtx" .Values.global.database.redis.secrets.secretManagement.externalSecretsOperator))) | indent 12 }}
            {{- include "harnesscommon.secrets.manageEnv" (dict "ctx" . "variableName" "REDIS_PASSWORD" "kubernetesSecretName" .Values.global.database.redis.secretName "kubernetesSecretKey" .Values.global.database.redis.passwordKey "extKubernetesSecretCtxs" (list .Values.secrets.kubernetesSecrets .Values.global.database.redis.secrets.kubernetesSecrets) "esoSecretCtxs" (list (dict "secretCtxIdentifier" "local" "secretCtx" .Values.secrets.secretManagement.externalSecretsOperator) (dict "secretCtxIdentifier" "global" "secretCtx" .Values.global.database.redis.secrets.secretManagement.externalSecretsOperator))) | indent 12 }}
            {{- include "harnesscommon.secrets.manageEnv" (dict "ctx" . "variableName" "EVENTS_FRAMEWORK_REDIS_USERNAME" "kubernetesSecretName" .Values.global.database.redis.secretName "kubernetesSecretKey" .Values.global.database.redis.userKey "extKubernetesSecretCtxs" (list .Values.secrets.kubernetesSecrets .Values.global.database.redis.secrets.kubernetesSecrets) "esoSecretCtxs" (list (dict "secretCtxIdentifier" "local" "secretCtx" .Values.secrets.secretManagement.externalSecretsOperator) (dict "secretCtxIdentifier" "global" "secretCtx" .Values.global.database.redis.secrets.secretManagement.externalSecretsOperator))) | indent 12 }}
            {{- include "harnesscommon.secrets.manageEnv" (dict "ctx" . "variableName" "EVENTS_FRAMEWORK_REDIS_PASSWORD" "kubernetesSecretName" .Values.global.database.redis.secretName "kubernetesSecretKey" .Values.global.database.redis.passwordKey "extKubernetesSecretCtxs" (list .Values.secrets.kubernetesSecrets .Values.global.database.redis.secrets.kubernetesSecrets) "esoSecretCtxs" (list (dict "secretCtxIdentifier" "local" "secretCtx" .Values.secrets.secretManagement.externalSecretsOperator) (dict "secretCtxIdentifier" "global" "secretCtx" .Values.global.database.redis.secrets.secretManagement.externalSecretsOperator))) | indent 12 }}
            {{- end }}
            {{- include "harnesscommon.secrets.manageEnv" (dict "ctx" . "variableName" "MONGO_USER" "kubernetesSecretName" .Values.global.database.mongo.secretName "kubernetesSecretKey" .Values.global.database.mongo.userKey "defaultKubernetesSecretName" "harness-secrets" "defaultKubernetesSecretKey" "mongodbUsername" "extKubernetesSecretCtxs" (list .Values.secrets.kubernetesSecrets .Values.global.database.redis.secrets.kubernetesSecrets) "esoSecretCtxs" (list (dict "secretCtxIdentifier" "local" "secretCtx" .Values.secrets.secretManagement.externalSecretsOperator) (dict "secretCtxIdentifier" "global" "secretCtx" .Values.global.database.redis.secrets.secretManagement.externalSecretsOperator))) | indent 12 }}
            {{- include "harnesscommon.secrets.manageEnv" (dict "ctx" . "variableName" "MONGO_PASSWORD" "kubernetesSecretName" .Values.global.database.mongo.secretName "kubernetesSecretKey" .Values.global.database.mongo.passwordKey "defaultKubernetesSecretName" "mongodb-replicaset-chart" "defaultKubernetesSecretKey" "mongodb-root-password" "extKubernetesSecretCtxs" (list .Values.secrets.kubernetesSecrets .Values.global.database.redis.secrets.kubernetesSecrets) "esoSecretCtxs" (list (dict "secretCtxIdentifier" "local" "secretCtx" .Values.secrets.secretManagement.externalSecretsOperator) (dict "secretCtxIdentifier" "global" "secretCtx" .Values.global.database.redis.secrets.secretManagement.externalSecretsOperator))) | indent 12 }}
            {{- include "harnesscommon.dbconnection.timescaleEnv" (dict "passwordVariableName" "TIMESCALEDB_PASSWORD" "userVariableName" "TIMESCALEDB_USERNAME" "context" $) | indent 12}}
            {{- include "harnesscommon.dbconnection.timescaleSslEnv" (dict "sslModeValue" "require" "certVariableName" "TIMESCALEDB_SSL_ROOT_CERT" "context" $ ) | nindent 12 }}
            - name: MONGO_URI
              value: {{ include "harnesscommon.dbconnection.mongoConnection" (dict "database" "harness" "context" $) }}
            - name: DMS_MONGO_URI
              value: {{ include "harnesscommon.dbconnection.mongoConnection" (dict "database" "dms-harness" "context" $) }}
            - name: NOTIFICATION_MONGO_URI
              value: {{ include "harnesscommon.dbconnection.mongoConnection" (dict "database" "notifications" "context" $) }}
            - name: TIMESCALEDB_URI
              value: {{ include "harnesscommon.dbconnection.timescaleConnection" (dict "protocol" "jdbc:postgresql" "database" "harness" "context" $) }}
            {{- if .Values.extraEnvVars }}
            {{- include "harnesscommon.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.lifecycleHooks }}
          lifecycle: {{- include "harnesscommon.tplvalues.render" (dict "value" .Values.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}

          livenessProbe:
            failureThreshold: 20
            initialDelaySeconds: 180
            httpGet:
              path: /api/version
              port: {{.Values.service.port}}
              scheme: HTTP
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          name: manager
          ports:
          {{- include "harnesscommon.monitoring.containerPort" . | nindent 12 }}
            - containerPort: {{.Values.service.grpcport}}
              protocol: TCP
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /api/health
              port: {{.Values.service.port}}
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - name: dynamic-iterator-config
              mountPath: /opt/harness/config
          {{- if .Values.global.mongoSSL }}
            - name: mongo-ssl-certs
              mountPath: /mongo
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
          {{- include "harnesscommon.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: dynamic-iterator-config
          configMap:
            name: iterator-config
            defaultMode: 420
      {{- if .Values.global.mongoSSL }}
        - name: mongo-ssl-certs
          secret:
            secretName: mongodb-replicaset-ssl-cert
      {{- end }}
      {{- if .Values.extraVolumes }}
      {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.extraVolumes "context" $ ) | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - harness-manager
            topologyKey: "kubernetes.io/hostname"
      {{- with .Values.affinity }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
