{{- if eq (include "harnesscommon.secrets.hasESOSecrets" (dict "secretsCtx" .Values.secrets)) "true" }}
    {{- $localESOSecretIdentifier := (printf "%s-ext-secret" $.Chart.Name) }}
    {{ include "harnesscommon.secrets.generateExternalSecret" (dict "secretsCtx" .Values.secrets "secretNamePrefix" $localESOSecretIdentifier) }}
    {{- print "\n---" }}
{{- end }}
{{- if eq (include "harnesscommon.secrets.hasESOSecrets" (dict "secretsCtx" .Values.redis.secrets)) "true" }}
    {{- $localESOSecretIdentifier := (printf "%s-%s-ext-secret" $.Chart.Name "redis") }}
    {{- include "harnesscommon.secrets.generateExternalSecret" (dict "secretsCtx" .Values.redis.secrets "secretNamePrefix" $localESOSecretIdentifier) }}
    {{- print "\n---" }}
{{- end }}
{{- if eq (include "harnesscommon.secrets.hasESOSecrets" (dict "secretsCtx" .Values.mongo.secrets)) "true" }}
    {{- $localESOSecretIdentifier := (printf "%s-%s-ext-secret" $.Chart.Name "mongo") }}
    {{- include "harnesscommon.secrets.generateExternalSecret" (dict "secretsCtx" .Values.mongo.secrets "secretNamePrefix" $localESOSecretIdentifier) }}
    {{- print "\n---" }}
{{- end }}
{{- if eq (include "harnesscommon.secrets.hasESOSecrets" (dict "secretsCtx" .Values.timescaledb.secrets)) "true" }}
    {{- $localESOSecretIdentifier := (printf "%s-%s-ext-secret" $.Chart.Name "timescaledb") }}
    {{- include "harnesscommon.secrets.generateExternalSecret" (dict "secretsCtx" .Values.timescaledb.secrets "secretNamePrefix" $localESOSecretIdentifier) }}
    {{- print "\n---" }}
{{- end }}
