{{- if .Values.global.secrets.app.external.enabled }}
{{- if .Values.global.secrets.app.external.kind.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cg-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: shared
  target:
    name: cg-manager-external-secret
    # this is how the Kind=Secret will look like
    template:
      engineVersion: v2
      data:
        SMTP_HOST: "{{ printf "{{ .smtp_host }}" }}"
        SMTP_USER: "{{ printf "{{ .smtp_user }}" }}"
        SMTP_PASSWORD: "{{ printf "{{ .smtp_password }}" }}"
  data:
  ## These keys MUST exist in your shared secret store
  - secretKey: smtp_host
    remoteRef:
      key: SMTP_HOST
  - secretKey: smtp_user
    remoteRef:
      key: SMTP_USERNAME
  - secretKey: smtp_password
    remoteRef:
      key: SMTP_PASSWORD
{{- end }}

{{- end}}
