DOCKER_FILE_PATH: /harness/harness-core/product/log-service/docker/Dockerfile-logservice-multistage
CONTEXT_PATH: /harness/harness-core
HELM_CHART_SOURCE_DIRECTORY: harness-core/product/log-service/chart
