openapi: 3.0.0
x-stoplight:
  id: cw2rng7ei2wad
info:
  title: idp-3-0-3
  version: '1.0'
  description: Harness Internal Developer Portal API Reference
servers:
  - url: 'https://api.harness.io'
paths:
  /v1/token:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/TokenResponseList'
      operationId: get-v1-token
      description: Get all tokens for a given account
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Sort'
      requestBody:
        $ref: '#/components/requestBodies/TokenRequest'
      security:
        - x-api-key: []
    post:
      summary: ''
      operationId: post-v1-token
      responses:
        '201':
          $ref: '#/components/responses/TokenResponse'
      description: Creates a token
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      security:
        - x-api-key: []
      requestBody:
        $ref: '#/components/requestBodies/TokenRequest'
  '/v1/token/{token}':
    parameters:
      - schema:
          type: string
        name: token
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/TokenResponse'
      operationId: get-v1-token-token
      description: Retrieves the specified token
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
    put:
      summary: ''
      operationId: put-v1-token-token
      responses:
        '200':
          $ref: '#/components/responses/TokenResponse'
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/TokenRequest'
      description: Updates the specified token
    delete:
      summary: ''
      operationId: delete-v1-token-token
      responses:
        '200':
          $ref: '#/components/responses/TokenResponse'
      description: Deletes the requested token
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
components:
  schemas:
    Token:
      title: Token
      x-stoplight:
        id: nfzxik84auzqi
      type: object
      properties:
        name:
          type: string
        secretIdentifier:
          type: string
    TokenRequest:
      title: TokenRequest
      x-stoplight:
        id: jmiar0p7kinb2
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    TokenResponse:
      title: TokenResponse
      x-stoplight:
        id: uf6lxsrsk2duk
      type: object
      properties:
        token:
          $ref: '#/components/schemas/Token'
        created:
          type: integer
          format: int64
        updated:
          type: integer
          format: int64
  parameters:
    AccountHeader:
      name: Harness-Account
      in: header
      required: false
      schema:
        type: string
      description: 'Identifier field of the account the resource is scoped to. This is required for Authorization methods other than the x-api-key header. If you are using the x-api-key header, this can be skipped.'
    Limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
      description: 'Pagination: Number of items to return'
    Page:
      name: page
      in: query
      required: false
      schema:
        type: integer
      description: "Pagination page number strategy: Specify the page number within the paginated collection related to the number of items in each page\t"
    Sort:
      name: sort
      in: query
      required: false
      schema:
        type: string
      description: Parameter on the basis of which sorting is done.
    TokenPathParam:
      name: token
      in: path
      required: true
      schema:
        type: string
      description: Identifier field of the token the resource is scoped to
  requestBodies:
    TokenRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TokenRequest'
  responses:
    TokenResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TokenResponse'
    TokenResponseList:
      description: Example response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/TokenResponse'
      headers:
        X-Total-Elements:
          schema:
            type: integer
          description: Total number of elements returned in Paginated response.
        X-Page-Number:
          schema:
            type: integer
          description: Page number in Paginated response.
        X-Page-Size:
          schema:
            type: integer
          description: Maximum page size in Paginated response.
  securitySchemes:
    x-api-key:
      name: x-api-key
      type: apiKey
      in: header
