#Any edit in this file should accompany an increment in version.
name : settingsConfiguration
version : 5
settings :
  - identifier: mandate_webhook_secrets_for_github_triggers_CD
    name: Mandate Webhook Secrets for Github Triggers - CD
    category: CD
    defaultValue: false
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: mandate_webhook_secrets_for_github_triggers_CI
    name: Mandate Webhook Secrets for Github Triggers - CI
    category: CI
    defaultValue: false
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: disable_harness_built_in_secret_manager
    name: Disable Harness Built-In Secret Manager
    category : CORE
    defaultValue: false
    valueType : BOOLEAN
    allowedScopes :
      - ACCOUNT

  - identifier: max_concurrent_pipelines_free_plan
    name: Max Concurrent Pipelines
    category : PMS
    defaultValue: 5
    groupIdentifier: max_concurrent_pipelines
    valueType : NUMBER
    allowedScopes :
      - ACCOUNT
  - identifier: max_concurrent_pipelines_team_plan
    name: Max Concurrent Pipelines
    category : PMS
    groupIdentifier: max_concurrent_pipelines
    defaultValue: 100
    valueType : NUMBER
    allowedScopes :
      - ACCOUNT
  - identifier: max_concurrent_pipelines_enterprise_plan
    name: Max Concurrent Pipelines
    category : PMS
    groupIdentifier: max_concurrent_pipelines
    defaultValue: 200
    valueType : NUMBER
    allowedScopes :
      - ACCOUNT

  - identifier: max_concurrent_nodes_free_plan
    name: Max Concurrent Nodes
    category : PMS
    groupIdentifier: max_concurrent_nodes
    defaultValue: 5
    valueType : NUMBER
    allowedScopes :
      - ACCOUNT
  - identifier: max_concurrent_nodes_team_plan
    name: Max Concurrent Nodes
    category : PMS
    groupIdentifier: max_concurrent_nodes
    defaultValue: 1000
    valueType : NUMBER
    allowedScopes :
      - ACCOUNT
  - identifier: max_concurrent_nodes_enterprise_plan
    name: Max Concurrent Nodes
    category : PMS
    groupIdentifier: max_concurrent_nodes
    defaultValue: 2000
    valueType : NUMBER
    allowedScopes :
      - ACCOUNT
