#Any edit in this file should accompany an increment in version.
name : settingsConfiguration
version : 5
settings :
  - identifier: mandate_webhook_secrets_for_github_triggers
    name: Mandate Webhook Secrets for Github Triggers
    category: CORE
    defaultValue: false
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: disable_harness_built_in_secret_manager
    name: Disable Harness Built-In Secret Manager
    category : CORE
    defaultValue: false
    valueType : BOOLEAN
    allowedScopes :
      - ACCOUNT
