{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: batch-processing-role
  namespace: {{ .Release.Namespace }}
  annotations: {}
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
      - get
      - list
      - watch
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs:
      - get
      - list
      - watch
      - create
{{- end }}
