# Default values for ci-manager
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  loadbalancerURL: ""
  airgap: false
  ingress:
    enabled: false
    className: harness
    hosts:
      - my-host.example.org
    tls:
      enabled: true
      secretName: ''
  istio:
    enabled: false
    gateway:
      create: false
    virtualService:
      gateways:
      hosts:
  imagePullSecrets: []
replicaCount: 1
maxSurge: 1
maxUnavailable: 0

config:
  CACHE_BACKEND: REDIS
  CACHE_CONFIG_REDIS_SENTINELS:
  CACHE_CONFIG_SENTINEL_MASTER_NAME: harness-redis
  CACHE_CONFIG_USE_SENTINEL: true
  DEPLOY_MODE: KUBERNETES_ONPREM
  MANAGER_TARGET:
  MANAGER_AUTHORITY:
  SCM_SERVICE_URI:
  PMS_TARGET:
  PMS_AUTHORITY:
  EVENTS_FRAMEWORK_REDIS_URL:
  EVENTS_FRAMEWORK_USE_SENTINEL:
  EVENTS_FRAMEWORK_SENTINEL_MASTER_NAME:
  EVENTS_FRAMEWORK_REDIS_SENTINELS:
  SHOULD_CONFIGURE_WITH_PMS: true
  ENABLE_DASHBOARD_TIMESCALE: true
  USE_REDIS_FOR_SDK_RESPONSE_EVENTS: true
  MANAGER_URL:
  LOG_SERVICE_GLOBAL_TOKEN: c76e567a-b341-404d-a8dd-d9738714eb82
  TI_SERVICE_GLOBAL_TOKEN: 78d16b66-4b4c-11eb-8377-acde48001122
  

image:
  registry: docker.io
  repository: harness/ci-manager-signed
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2804"
  digest: ""
  imagePullSecrets: []

securityImage:
  image:
    registry: docker.io
    repository: harness/sto-plugin
    tag: latest
    digest: ""
    imagePullSecrets: []

waitForInitContainer:
  image:
    registry: docker.io
    repository: harness/helm-init-container
    pullPolicy: IfNotPresent
    tag: "latest"
    digest: ""
    imagePullSecrets: []

ci_images:
  addon:
    image:
      registry: docker.io
      digest: ""
      tag: "1.16.4"
      repository: harness/ci-addon
      imagePullSecrets: []

  lite_engine:
    image:
      registry: docker.io
      digest: ""
      tag: "1.16.4"
      repository: harness/ci-lite-engine
      imagePullSecrets: []

  git_clone:
    image:
      registry: docker.io
      digest: ""
      tag: "1.2.7-rootless"
      repository: harness/drone-git
      imagePullSecrets: []

  kaniko:
    image:
      registry: docker.io
      digest: ""
      tag: "1.7.0"
      repository: plugins/kaniko
      imagePullSecrets: []

  kaniko_ecr:
    image:
      registry: docker.io
      digest: ""
      tag: "1.7.0"
      repository: plugins/kaniko-ecr
      imagePullSecrets: []

  kaniko_gcr:
    image:
      registry: docker.io
      digest: ""
      tag: "1.7.0"
      repository: plugins/kaniko-gcr
      imagePullSecrets: []
      
  kaniko_acr:
    image:
      registry: docker.io
      digest: ""
      tag: "1.7.1"
      repository: plugins/kaniko-acr
      imagePullSecrets: []

  gcs_upload:
    image:
      registry: docker.io
      digest: ""
      tag: "1.3.0"
      repository: plugins/gcs
      imagePullSecrets: []

  s3_upload:
    image:
      registry: docker.io
      digest: ""
      tag: "1.2.0"
      repository: plugins/s3
      imagePullSecrets: []

  artifactory_upload:
    image:
      registry: docker.io
      digest: ""
      tag: "1.2.0"
      repository: plugins/artifactory
      imagePullSecrets: []

  gcs_cache:
    image:
      registry: docker.io
      digest: ""
      tag: "1.4.6"
      repository: plugins/cache
      imagePullSecrets: []

  s3_cache:
    image:
      registry: docker.io
      digest: ""
      tag: "1.4.6"
      repository: plugins/cache
      imagePullSecrets: []

stoServiceGlobalToken:
  name: harness-secrets
  key: stoAppHarnessToken

mongoSecrets:
  userName:
    name: harness-secrets
    key: mongodbUsername
  password:
    name: mongodb-replicaset-chart
    key: mongodb-root-password

timescaleSecret:
  password:
    name: harness-secrets
    key: timescaledbPostgresPassword

java:
  memory: 4096

appLogLevel: INFO

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "harness-default"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsUser: 65534
  runAsNonRoot: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 7090
  grpcport: 9979

resources:
  limits:
    cpu: 1
    memory: 8192Mi
  requests:
    cpu: 1
    memory: 1400Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
