DOCKER_FILE_PATH: /harness/harness-core/batch-processing/build/container/Dockerfile-batch-processing-multistage
CONTEXT_PATH: /harness/harness-core
HELM_CHART_SOURCE_DIRECTORY: harness-core/batch-processing/chart
