apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "log-service.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      {{- include "log-service.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{.Values.maxSurge}}
      maxUnavailable: {{.Values.maxUnavailable}}
  template:
    metadata:
      {{- if or .Values.global.commonAnnotations .Values.podAnnotations }}
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.global.commonAnnotations }}
          {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "log-service.selectorLabels" . | nindent 8 }}
        {{- if .Values.global.commonLabels }}
        {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.podLabels }}
        {{- include "harnesscommon.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: 30
      {{ include "log-service.pullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "log-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: log-service
        envFrom:
        - configMapRef:
            name: log-service
        env:
          {{- if .Values.s3.accessKeyId }}
          - name: LOG_SERVICE_S3_ACCESS_KEY_ID
            value: {{ .Values.s3.accessKeyId  }}
          {{- else }}
          - name: LOG_SERVICE_S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.logServiceS3AccessKeyID.name }}
                key: {{ .Values.logServiceS3AccessKeyID.key }}
          {{- end }}
          {{- if .Values.s3.secretAccessKey }}
          - name: LOG_SERVICE_S3_SECRET_ACCESS_KEY
            value: {{ .Values.s3.secretAccessKey }}
          {{- else }}
          - name: LOG_SERVICE_S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.logServiceS3SecretAccessKey.name }}
                key: {{ .Values.logServiceS3SecretAccessKey.key }}
          {{- end }}
          {{- $localESOSecretCtxIdentifier := (include "harnesscommon.secrets.localESOSecretCtxIdentifier" (dict "ctx" $ )) }}
          {{- include "harnesscommon.secrets.manageEnv" (dict "ctx" . "variableName" "LOG_SERVICE_GLOBAL_TOKEN" "defaultKubernetesSecretName" "log-service-secret" "defaultKubernetesSecretKey" "LOG_SERVICE_GLOBAL_TOKEN" "extKubernetesSecretCtxs" (list .Values.secrets.kubernetesSecrets) "esoSecretCtxs" (list (dict "secretCtxIdentifier" $localESOSecretCtxIdentifier "secretCtx" .Values.secrets.secretManagement.externalSecretsOperator))) | indent 10 }}
          {{- include "harnesscommon.secrets.manageEnv" (dict "ctx" . "variableName" "LOG_SERVICE_SECRET" "defaultKubernetesSecretName" "log-service-secret" "defaultKubernetesSecretKey" "LOG_SERVICE_SECRET" "extKubernetesSecretCtxs" (list .Values.secrets.kubernetesSecrets) "esoSecretCtxs" (list (dict "secretCtxIdentifier" $localESOSecretCtxIdentifier "secretCtx" .Values.secrets.secretManagement.externalSecretsOperator))) | indent 10 }}
          {{- include "harnesscommon.dbconnectionv2.redisEnv" (dict "ctx" . "userVariableName" "LOG_SERVICE_REDIS_USERNAME" "passwordVariableName" "LOG_SERVICE_REDIS_PASSWORD" "localRedisCtx" .Values.redis "globalRedisCtx" .Values.global.database.redis) | indent 10 }}
          - name: LOG_SERVICE_REDIS_DISABLE_EXPIRY_WATCHER
            value: {{ .Values.redis.disableWatcher | quote }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-log-svc
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: http-log-svc
          initialDelaySeconds: 10
          periodSeconds: 10
        image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        ports:
        - name: http-log-svc
          containerPort: {{ .Values.service.port }}
          protocol: "TCP"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.lifecycleHooks }}
        lifecycle: {{- include "harnesscommon.tplvalues.render" (dict "value" .Values.lifecycleHooks "context" $) | nindent 12 }}
        {{- end }}
        volumeMounts:
        {{- if .Values.extraVolumeMounts }}
        {{- include "harnesscommon.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" $) | nindent 12 }}
        {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - log-service
            topologyKey: "kubernetes.io/hostname"
      {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.extraVolumes }}
      volumes:
      {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.extraVolumes "context" $ ) | nindent 8 }}
      {{- end }}
