BUILD_SCRIPT_PATH: 100-migrator/build/feature_build.sh
DOCKER_FILE_PATH: /harness/harness-core/dist/migrator/Dockerfile-gcr
CONTEXT_PATH: /harness/harness-core/dist/migrator
ARTIFACT_REPO: harness/feature-migrator-openjdk-8u242
HELM_CHART_SOURCE_DIRECTORY: harness-core/100-migrator/chart
HELM_REPO_NAME: us-west1-docker.pkg.dev/platform-205701/harness-helm-artifacts
BUILD_STEP_RESOURCE_CPU: 1000m
BUILD_STEP_RESOURCE_MEMORY: 4Gi
