BUILD_SCRIPT_PATH="315-sto-manager/build/feature_build.sh"
DOCKER_FILE_PATH="/harness/dist/sto-manager-service/Dockerfile-gcr-ubi"
CONTEXT_PATH="/harness/dist/sto-manager-service"
CONFIG_FOLDER_PATH="harness-core/sto-manager-service"
ARTIFACT_REPO="harness/saas-openjdk-8u242/sto-manager"
HELM_CHART_REPO="sto-manager-service/chart"
HELM_PUBLISH_REPO="us-west1-docker.pkg.dev/platform-205701/harness-helm-artifacts"
BUILD_STEP_RESOURCE_CPU="5000m"
BUILD_STEP_RESOURCE_MEMORY="15Gi"